/**
 * Idempotent (`IF NOT EXISTS`) DDL for the per-block child tables of every
 * versioned/blocks-bearing collection and global (`*_blocks_*`, `_*_v_blocks_*`).
 *
 * These used to live in four hand-run `.sql` files applied by `deploy:database`
 * via `wrangler d1 execute --remote`, which a fresh install never ran - so a new
 * database was missing 56 tables and the page-builder schema set failed. They
 * are now part of `runInternalMigrate` (step 3b), so the deploy button and the
 * first-run bootstrap create them too. Safe to replay on an existing database.
 */
export const BLOCKS_RELS_STATEMENTS: string[] = [
  "CREATE TABLE IF NOT EXISTS `posts_blocks_hero` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `heading` text, `subheading` text, `background_image_id` integer, `primary_cta_label` text, `primary_cta_url` text, `secondary_cta_label` text, `secondary_cta_url` text, `block_name` text, FOREIGN KEY (`background_image_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null, FOREIGN KEY (`_parent_id`) REFERENCES `posts`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `posts_blocks_hero_order_idx` ON `posts_blocks_hero` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `posts_blocks_hero_parent_id_idx` ON `posts_blocks_hero` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `posts_blocks_hero_path_idx` ON `posts_blocks_hero` (`_path`)",
  "CREATE INDEX IF NOT EXISTS `posts_blocks_hero_background_image_idx` ON `posts_blocks_hero` (`background_image_id`)",
  "CREATE TABLE IF NOT EXISTS `posts_blocks_rich_text` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `content` text, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `posts`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `posts_blocks_rich_text_order_idx` ON `posts_blocks_rich_text` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `posts_blocks_rich_text_parent_id_idx` ON `posts_blocks_rich_text` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `posts_blocks_rich_text_path_idx` ON `posts_blocks_rich_text` (`_path`)",
  "CREATE TABLE IF NOT EXISTS `posts_blocks_image_text` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `image_id` integer, `content` text, `image_side` text DEFAULT 'left', `block_name` text, FOREIGN KEY (`image_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null, FOREIGN KEY (`_parent_id`) REFERENCES `posts`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `posts_blocks_image_text_order_idx` ON `posts_blocks_image_text` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `posts_blocks_image_text_parent_id_idx` ON `posts_blocks_image_text` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `posts_blocks_image_text_path_idx` ON `posts_blocks_image_text` (`_path`)",
  "CREATE INDEX IF NOT EXISTS `posts_blocks_image_text_image_idx` ON `posts_blocks_image_text` (`image_id`)",
  "CREATE TABLE IF NOT EXISTS `posts_blocks_product_grid` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `heading` text, `category` text, `limit` numeric DEFAULT 4, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `posts`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `posts_blocks_product_grid_order_idx` ON `posts_blocks_product_grid` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `posts_blocks_product_grid_parent_id_idx` ON `posts_blocks_product_grid` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `posts_blocks_product_grid_path_idx` ON `posts_blocks_product_grid` (`_path`)",
  "CREATE TABLE IF NOT EXISTS `posts_blocks_event_grid` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `heading` text, `show_past` integer DEFAULT false, `limit` numeric DEFAULT 3, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `posts`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `posts_blocks_event_grid_order_idx` ON `posts_blocks_event_grid` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `posts_blocks_event_grid_parent_id_idx` ON `posts_blocks_event_grid` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `posts_blocks_event_grid_path_idx` ON `posts_blocks_event_grid` (`_path`)",
  "CREATE TABLE IF NOT EXISTS `posts_blocks_gallery` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `heading` text, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `posts`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `posts_blocks_gallery_order_idx` ON `posts_blocks_gallery` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `posts_blocks_gallery_parent_id_idx` ON `posts_blocks_gallery` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `posts_blocks_gallery_path_idx` ON `posts_blocks_gallery` (`_path`)",
  "CREATE TABLE IF NOT EXISTS `posts_blocks_faq` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `heading` text DEFAULT 'Frequently asked questions', `source` text DEFAULT 'category', `category` text, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `posts`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `posts_blocks_faq_order_idx` ON `posts_blocks_faq` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `posts_blocks_faq_parent_id_idx` ON `posts_blocks_faq` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `posts_blocks_faq_path_idx` ON `posts_blocks_faq` (`_path`)",
  "CREATE TABLE IF NOT EXISTS `posts_blocks_cta_banner` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `heading` text, `text` text, `button_label` text, `button_url` text, `style` text DEFAULT 'dark', `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `posts`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `posts_blocks_cta_banner_order_idx` ON `posts_blocks_cta_banner` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `posts_blocks_cta_banner_parent_id_idx` ON `posts_blocks_cta_banner` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `posts_blocks_cta_banner_path_idx` ON `posts_blocks_cta_banner` (`_path`)",
  "CREATE TABLE IF NOT EXISTS `posts_rels` ( `id` integer PRIMARY KEY NOT NULL, `order` integer, `parent_id` integer NOT NULL, `path` text NOT NULL, `media_id` integer, `faqs_id` integer, FOREIGN KEY (`parent_id`) REFERENCES `posts`(`id`) ON UPDATE no action ON DELETE cascade, FOREIGN KEY (`media_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE cascade, FOREIGN KEY (`faqs_id`) REFERENCES `faqs`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `posts_rels_order_idx` ON `posts_rels` (`order`)",
  "CREATE INDEX IF NOT EXISTS `posts_rels_parent_idx` ON `posts_rels` (`parent_id`)",
  "CREATE INDEX IF NOT EXISTS `posts_rels_path_idx` ON `posts_rels` (`path`)",
  "CREATE INDEX IF NOT EXISTS `posts_rels_media_id_idx` ON `posts_rels` (`media_id`)",
  "CREATE INDEX IF NOT EXISTS `posts_rels_faqs_id_idx` ON `posts_rels` (`faqs_id`)",
  "CREATE TABLE IF NOT EXISTS `_posts_v_blocks_hero` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` integer PRIMARY KEY NOT NULL, `heading` text, `subheading` text, `background_image_id` integer, `primary_cta_label` text, `primary_cta_url` text, `secondary_cta_label` text, `secondary_cta_url` text, `_uuid` text, `block_name` text, FOREIGN KEY (`background_image_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null, FOREIGN KEY (`_parent_id`) REFERENCES `_posts_v`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `_posts_v_blocks_hero_order_idx` ON `_posts_v_blocks_hero` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `_posts_v_blocks_hero_parent_id_idx` ON `_posts_v_blocks_hero` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `_posts_v_blocks_hero_path_idx` ON `_posts_v_blocks_hero` (`_path`)",
  "CREATE INDEX IF NOT EXISTS `_posts_v_blocks_hero_background_image_idx` ON `_posts_v_blocks_hero` (`background_image_id`)",
  "CREATE TABLE IF NOT EXISTS `_posts_v_blocks_rich_text` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` integer PRIMARY KEY NOT NULL, `content` text, `_uuid` text, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `_posts_v`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `_posts_v_blocks_rich_text_order_idx` ON `_posts_v_blocks_rich_text` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `_posts_v_blocks_rich_text_parent_id_idx` ON `_posts_v_blocks_rich_text` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `_posts_v_blocks_rich_text_path_idx` ON `_posts_v_blocks_rich_text` (`_path`)",
  "CREATE TABLE IF NOT EXISTS `_posts_v_blocks_image_text` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` integer PRIMARY KEY NOT NULL, `image_id` integer, `content` text, `image_side` text DEFAULT 'left', `_uuid` text, `block_name` text, FOREIGN KEY (`image_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null, FOREIGN KEY (`_parent_id`) REFERENCES `_posts_v`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `_posts_v_blocks_image_text_order_idx` ON `_posts_v_blocks_image_text` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `_posts_v_blocks_image_text_parent_id_idx` ON `_posts_v_blocks_image_text` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `_posts_v_blocks_image_text_path_idx` ON `_posts_v_blocks_image_text` (`_path`)",
  "CREATE INDEX IF NOT EXISTS `_posts_v_blocks_image_text_image_idx` ON `_posts_v_blocks_image_text` (`image_id`)",
  "CREATE TABLE IF NOT EXISTS `_posts_v_blocks_product_grid` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` integer PRIMARY KEY NOT NULL, `heading` text, `category` text, `limit` numeric DEFAULT 4, `_uuid` text, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `_posts_v`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `_posts_v_blocks_product_grid_order_idx` ON `_posts_v_blocks_product_grid` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `_posts_v_blocks_product_grid_parent_id_idx` ON `_posts_v_blocks_product_grid` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `_posts_v_blocks_product_grid_path_idx` ON `_posts_v_blocks_product_grid` (`_path`)",
  "CREATE TABLE IF NOT EXISTS `_posts_v_blocks_event_grid` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` integer PRIMARY KEY NOT NULL, `heading` text, `show_past` integer DEFAULT false, `limit` numeric DEFAULT 3, `_uuid` text, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `_posts_v`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `_posts_v_blocks_event_grid_order_idx` ON `_posts_v_blocks_event_grid` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `_posts_v_blocks_event_grid_parent_id_idx` ON `_posts_v_blocks_event_grid` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `_posts_v_blocks_event_grid_path_idx` ON `_posts_v_blocks_event_grid` (`_path`)",
  "CREATE TABLE IF NOT EXISTS `_posts_v_blocks_gallery` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` integer PRIMARY KEY NOT NULL, `heading` text, `_uuid` text, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `_posts_v`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `_posts_v_blocks_gallery_order_idx` ON `_posts_v_blocks_gallery` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `_posts_v_blocks_gallery_parent_id_idx` ON `_posts_v_blocks_gallery` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `_posts_v_blocks_gallery_path_idx` ON `_posts_v_blocks_gallery` (`_path`)",
  "CREATE TABLE IF NOT EXISTS `_posts_v_blocks_faq` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` integer PRIMARY KEY NOT NULL, `heading` text DEFAULT 'Frequently asked questions', `source` text DEFAULT 'category', `category` text, `_uuid` text, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `_posts_v`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `_posts_v_blocks_faq_order_idx` ON `_posts_v_blocks_faq` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `_posts_v_blocks_faq_parent_id_idx` ON `_posts_v_blocks_faq` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `_posts_v_blocks_faq_path_idx` ON `_posts_v_blocks_faq` (`_path`)",
  "CREATE TABLE IF NOT EXISTS `_posts_v_blocks_cta_banner` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` integer PRIMARY KEY NOT NULL, `heading` text, `text` text, `button_label` text, `button_url` text, `style` text DEFAULT 'dark', `_uuid` text, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `_posts_v`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `_posts_v_blocks_cta_banner_order_idx` ON `_posts_v_blocks_cta_banner` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `_posts_v_blocks_cta_banner_parent_id_idx` ON `_posts_v_blocks_cta_banner` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `_posts_v_blocks_cta_banner_path_idx` ON `_posts_v_blocks_cta_banner` (`_path`)",
  "CREATE TABLE IF NOT EXISTS `_posts_v_rels` ( `id` integer PRIMARY KEY NOT NULL, `order` integer, `parent_id` integer NOT NULL, `path` text NOT NULL, `media_id` integer, `faqs_id` integer, FOREIGN KEY (`parent_id`) REFERENCES `_posts_v`(`id`) ON UPDATE no action ON DELETE cascade, FOREIGN KEY (`media_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE cascade, FOREIGN KEY (`faqs_id`) REFERENCES `faqs`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `_posts_v_rels_order_idx` ON `_posts_v_rels` (`order`)",
  "CREATE INDEX IF NOT EXISTS `_posts_v_rels_parent_idx` ON `_posts_v_rels` (`parent_id`)",
  "CREATE INDEX IF NOT EXISTS `_posts_v_rels_path_idx` ON `_posts_v_rels` (`path`)",
  "CREATE INDEX IF NOT EXISTS `_posts_v_rels_media_id_idx` ON `_posts_v_rels` (`media_id`)",
  "CREATE INDEX IF NOT EXISTS `_posts_v_rels_faqs_id_idx` ON `_posts_v_rels` (`faqs_id`)",
  "CREATE TABLE IF NOT EXISTS `products_blocks_hero` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `heading` text, `subheading` text, `background_image_id` integer, `primary_cta_label` text, `primary_cta_url` text, `secondary_cta_label` text, `secondary_cta_url` text, `block_name` text, FOREIGN KEY (`background_image_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null, FOREIGN KEY (`_parent_id`) REFERENCES `products`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `products_blocks_hero_order_idx` ON `products_blocks_hero` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `products_blocks_hero_parent_id_idx` ON `products_blocks_hero` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `products_blocks_hero_path_idx` ON `products_blocks_hero` (`_path`)",
  "CREATE INDEX IF NOT EXISTS `products_blocks_hero_background_image_idx` ON `products_blocks_hero` (`background_image_id`)",
  "CREATE TABLE IF NOT EXISTS `products_blocks_rich_text` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `content` text, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `products`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `products_blocks_rich_text_order_idx` ON `products_blocks_rich_text` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `products_blocks_rich_text_parent_id_idx` ON `products_blocks_rich_text` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `products_blocks_rich_text_path_idx` ON `products_blocks_rich_text` (`_path`)",
  "CREATE TABLE IF NOT EXISTS `products_blocks_image_text` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `image_id` integer, `content` text, `image_side` text DEFAULT 'left', `block_name` text, FOREIGN KEY (`image_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null, FOREIGN KEY (`_parent_id`) REFERENCES `products`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `products_blocks_image_text_order_idx` ON `products_blocks_image_text` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `products_blocks_image_text_parent_id_idx` ON `products_blocks_image_text` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `products_blocks_image_text_path_idx` ON `products_blocks_image_text` (`_path`)",
  "CREATE INDEX IF NOT EXISTS `products_blocks_image_text_image_idx` ON `products_blocks_image_text` (`image_id`)",
  "CREATE TABLE IF NOT EXISTS `products_blocks_product_grid` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `heading` text, `category` text, `limit` numeric DEFAULT 4, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `products`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `products_blocks_product_grid_order_idx` ON `products_blocks_product_grid` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `products_blocks_product_grid_parent_id_idx` ON `products_blocks_product_grid` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `products_blocks_product_grid_path_idx` ON `products_blocks_product_grid` (`_path`)",
  "CREATE TABLE IF NOT EXISTS `products_blocks_event_grid` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `heading` text, `show_past` integer DEFAULT false, `limit` numeric DEFAULT 3, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `products`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `products_blocks_event_grid_order_idx` ON `products_blocks_event_grid` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `products_blocks_event_grid_parent_id_idx` ON `products_blocks_event_grid` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `products_blocks_event_grid_path_idx` ON `products_blocks_event_grid` (`_path`)",
  "CREATE TABLE IF NOT EXISTS `products_blocks_gallery` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `heading` text, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `products`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `products_blocks_gallery_order_idx` ON `products_blocks_gallery` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `products_blocks_gallery_parent_id_idx` ON `products_blocks_gallery` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `products_blocks_gallery_path_idx` ON `products_blocks_gallery` (`_path`)",
  "CREATE TABLE IF NOT EXISTS `products_blocks_faq` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `heading` text DEFAULT 'Frequently asked questions', `source` text DEFAULT 'category', `category` text, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `products`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `products_blocks_faq_order_idx` ON `products_blocks_faq` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `products_blocks_faq_parent_id_idx` ON `products_blocks_faq` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `products_blocks_faq_path_idx` ON `products_blocks_faq` (`_path`)",
  "CREATE TABLE IF NOT EXISTS `products_blocks_cta_banner` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `heading` text, `text` text, `button_label` text, `button_url` text, `style` text DEFAULT 'dark', `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `products`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `products_blocks_cta_banner_order_idx` ON `products_blocks_cta_banner` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `products_blocks_cta_banner_parent_id_idx` ON `products_blocks_cta_banner` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `products_blocks_cta_banner_path_idx` ON `products_blocks_cta_banner` (`_path`)",
  "CREATE TABLE IF NOT EXISTS `_products_v_blocks_hero` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` integer PRIMARY KEY NOT NULL, `heading` text, `subheading` text, `background_image_id` integer, `primary_cta_label` text, `primary_cta_url` text, `secondary_cta_label` text, `secondary_cta_url` text, `_uuid` text, `block_name` text, FOREIGN KEY (`background_image_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null, FOREIGN KEY (`_parent_id`) REFERENCES `_products_v`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `_products_v_blocks_hero_order_idx` ON `_products_v_blocks_hero` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `_products_v_blocks_hero_parent_id_idx` ON `_products_v_blocks_hero` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `_products_v_blocks_hero_path_idx` ON `_products_v_blocks_hero` (`_path`)",
  "CREATE INDEX IF NOT EXISTS `_products_v_blocks_hero_background_image_idx` ON `_products_v_blocks_hero` (`background_image_id`)",
  "CREATE TABLE IF NOT EXISTS `_products_v_blocks_rich_text` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` integer PRIMARY KEY NOT NULL, `content` text, `_uuid` text, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `_products_v`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `_products_v_blocks_rich_text_order_idx` ON `_products_v_blocks_rich_text` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `_products_v_blocks_rich_text_parent_id_idx` ON `_products_v_blocks_rich_text` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `_products_v_blocks_rich_text_path_idx` ON `_products_v_blocks_rich_text` (`_path`)",
  "CREATE TABLE IF NOT EXISTS `_products_v_blocks_image_text` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` integer PRIMARY KEY NOT NULL, `image_id` integer, `content` text, `image_side` text DEFAULT 'left', `_uuid` text, `block_name` text, FOREIGN KEY (`image_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null, FOREIGN KEY (`_parent_id`) REFERENCES `_products_v`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `_products_v_blocks_image_text_order_idx` ON `_products_v_blocks_image_text` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `_products_v_blocks_image_text_parent_id_idx` ON `_products_v_blocks_image_text` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `_products_v_blocks_image_text_path_idx` ON `_products_v_blocks_image_text` (`_path`)",
  "CREATE INDEX IF NOT EXISTS `_products_v_blocks_image_text_image_idx` ON `_products_v_blocks_image_text` (`image_id`)",
  "CREATE TABLE IF NOT EXISTS `_products_v_blocks_product_grid` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` integer PRIMARY KEY NOT NULL, `heading` text, `category` text, `limit` numeric DEFAULT 4, `_uuid` text, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `_products_v`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `_products_v_blocks_product_grid_order_idx` ON `_products_v_blocks_product_grid` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `_products_v_blocks_product_grid_parent_id_idx` ON `_products_v_blocks_product_grid` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `_products_v_blocks_product_grid_path_idx` ON `_products_v_blocks_product_grid` (`_path`)",
  "CREATE TABLE IF NOT EXISTS `_products_v_blocks_event_grid` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` integer PRIMARY KEY NOT NULL, `heading` text, `show_past` integer DEFAULT false, `limit` numeric DEFAULT 3, `_uuid` text, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `_products_v`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `_products_v_blocks_event_grid_order_idx` ON `_products_v_blocks_event_grid` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `_products_v_blocks_event_grid_parent_id_idx` ON `_products_v_blocks_event_grid` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `_products_v_blocks_event_grid_path_idx` ON `_products_v_blocks_event_grid` (`_path`)",
  "CREATE TABLE IF NOT EXISTS `_products_v_blocks_gallery` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` integer PRIMARY KEY NOT NULL, `heading` text, `_uuid` text, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `_products_v`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `_products_v_blocks_gallery_order_idx` ON `_products_v_blocks_gallery` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `_products_v_blocks_gallery_parent_id_idx` ON `_products_v_blocks_gallery` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `_products_v_blocks_gallery_path_idx` ON `_products_v_blocks_gallery` (`_path`)",
  "CREATE TABLE IF NOT EXISTS `_products_v_blocks_faq` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` integer PRIMARY KEY NOT NULL, `heading` text DEFAULT 'Frequently asked questions', `source` text DEFAULT 'category', `category` text, `_uuid` text, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `_products_v`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `_products_v_blocks_faq_order_idx` ON `_products_v_blocks_faq` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `_products_v_blocks_faq_parent_id_idx` ON `_products_v_blocks_faq` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `_products_v_blocks_faq_path_idx` ON `_products_v_blocks_faq` (`_path`)",
  "CREATE TABLE IF NOT EXISTS `_products_v_blocks_cta_banner` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` integer PRIMARY KEY NOT NULL, `heading` text, `text` text, `button_label` text, `button_url` text, `style` text DEFAULT 'dark', `_uuid` text, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `_products_v`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `_products_v_blocks_cta_banner_order_idx` ON `_products_v_blocks_cta_banner` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `_products_v_blocks_cta_banner_parent_id_idx` ON `_products_v_blocks_cta_banner` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `_products_v_blocks_cta_banner_path_idx` ON `_products_v_blocks_cta_banner` (`_path`)",
  "CREATE TABLE IF NOT EXISTS `blog_settings_blocks_hero` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `heading` text NOT NULL, `subheading` text, `background_image_id` integer, `primary_cta_label` text, `primary_cta_url` text, `secondary_cta_label` text, `secondary_cta_url` text, `block_name` text, FOREIGN KEY (`background_image_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null, FOREIGN KEY (`_parent_id`) REFERENCES `blog_settings`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `blog_settings_blocks_hero_order_idx` ON `blog_settings_blocks_hero` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `blog_settings_blocks_hero_parent_id_idx` ON `blog_settings_blocks_hero` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `blog_settings_blocks_hero_path_idx` ON `blog_settings_blocks_hero` (`_path`)",
  "CREATE INDEX IF NOT EXISTS `blog_settings_blocks_hero_background_image_idx` ON `blog_settings_blocks_hero` (`background_image_id`)",
  "CREATE TABLE IF NOT EXISTS `blog_settings_blocks_rich_text` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `content` text NOT NULL, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `blog_settings`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `blog_settings_blocks_rich_text_order_idx` ON `blog_settings_blocks_rich_text` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `blog_settings_blocks_rich_text_parent_id_idx` ON `blog_settings_blocks_rich_text` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `blog_settings_blocks_rich_text_path_idx` ON `blog_settings_blocks_rich_text` (`_path`)",
  "CREATE TABLE IF NOT EXISTS `blog_settings_blocks_image_text` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `image_id` integer NOT NULL, `content` text NOT NULL, `image_side` text DEFAULT 'left', `block_name` text, FOREIGN KEY (`image_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null, FOREIGN KEY (`_parent_id`) REFERENCES `blog_settings`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `blog_settings_blocks_image_text_order_idx` ON `blog_settings_blocks_image_text` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `blog_settings_blocks_image_text_parent_id_idx` ON `blog_settings_blocks_image_text` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `blog_settings_blocks_image_text_path_idx` ON `blog_settings_blocks_image_text` (`_path`)",
  "CREATE INDEX IF NOT EXISTS `blog_settings_blocks_image_text_image_idx` ON `blog_settings_blocks_image_text` (`image_id`)",
  "CREATE TABLE IF NOT EXISTS `blog_settings_blocks_product_grid` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `heading` text, `category` text, `limit` numeric DEFAULT 4, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `blog_settings`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `blog_settings_blocks_product_grid_order_idx` ON `blog_settings_blocks_product_grid` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `blog_settings_blocks_product_grid_parent_id_idx` ON `blog_settings_blocks_product_grid` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `blog_settings_blocks_product_grid_path_idx` ON `blog_settings_blocks_product_grid` (`_path`)",
  "CREATE TABLE IF NOT EXISTS `blog_settings_blocks_event_grid` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `heading` text, `show_past` integer DEFAULT false, `limit` numeric DEFAULT 3, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `blog_settings`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `blog_settings_blocks_event_grid_order_idx` ON `blog_settings_blocks_event_grid` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `blog_settings_blocks_event_grid_parent_id_idx` ON `blog_settings_blocks_event_grid` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `blog_settings_blocks_event_grid_path_idx` ON `blog_settings_blocks_event_grid` (`_path`)",
  "CREATE TABLE IF NOT EXISTS `blog_settings_blocks_gallery` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `heading` text, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `blog_settings`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `blog_settings_blocks_gallery_order_idx` ON `blog_settings_blocks_gallery` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `blog_settings_blocks_gallery_parent_id_idx` ON `blog_settings_blocks_gallery` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `blog_settings_blocks_gallery_path_idx` ON `blog_settings_blocks_gallery` (`_path`)",
  "CREATE TABLE IF NOT EXISTS `blog_settings_blocks_faq` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `heading` text DEFAULT 'Frequently asked questions', `source` text DEFAULT 'category', `category` text, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `blog_settings`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `blog_settings_blocks_faq_order_idx` ON `blog_settings_blocks_faq` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `blog_settings_blocks_faq_parent_id_idx` ON `blog_settings_blocks_faq` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `blog_settings_blocks_faq_path_idx` ON `blog_settings_blocks_faq` (`_path`)",
  "CREATE TABLE IF NOT EXISTS `blog_settings_blocks_cta_banner` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `heading` text NOT NULL, `text` text, `button_label` text, `button_url` text, `style` text DEFAULT 'dark', `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `blog_settings`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `blog_settings_blocks_cta_banner_order_idx` ON `blog_settings_blocks_cta_banner` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `blog_settings_blocks_cta_banner_parent_id_idx` ON `blog_settings_blocks_cta_banner` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `blog_settings_blocks_cta_banner_path_idx` ON `blog_settings_blocks_cta_banner` (`_path`)",
  "CREATE TABLE IF NOT EXISTS `blog_settings_rels` ( `id` integer PRIMARY KEY NOT NULL, `order` integer, `parent_id` integer NOT NULL, `path` text NOT NULL, `media_id` integer, `faqs_id` integer, FOREIGN KEY (`parent_id`) REFERENCES `blog_settings`(`id`) ON UPDATE no action ON DELETE cascade, FOREIGN KEY (`media_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE cascade, FOREIGN KEY (`faqs_id`) REFERENCES `faqs`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `blog_settings_rels_order_idx` ON `blog_settings_rels` (`order`)",
  "CREATE INDEX IF NOT EXISTS `blog_settings_rels_parent_idx` ON `blog_settings_rels` (`parent_id`)",
  "CREATE INDEX IF NOT EXISTS `blog_settings_rels_path_idx` ON `blog_settings_rels` (`path`)",
  "CREATE INDEX IF NOT EXISTS `blog_settings_rels_media_id_idx` ON `blog_settings_rels` (`media_id`)",
  "CREATE INDEX IF NOT EXISTS `blog_settings_rels_faqs_id_idx` ON `blog_settings_rels` (`faqs_id`)",
  "CREATE TABLE IF NOT EXISTS `faq_settings_blocks_hero` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `heading` text NOT NULL, `subheading` text, `background_image_id` integer, `primary_cta_label` text, `primary_cta_url` text, `secondary_cta_label` text, `secondary_cta_url` text, `block_name` text, FOREIGN KEY (`background_image_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null, FOREIGN KEY (`_parent_id`) REFERENCES `faq_settings`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `faq_settings_blocks_hero_order_idx` ON `faq_settings_blocks_hero` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `faq_settings_blocks_hero_parent_id_idx` ON `faq_settings_blocks_hero` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `faq_settings_blocks_hero_path_idx` ON `faq_settings_blocks_hero` (`_path`)",
  "CREATE INDEX IF NOT EXISTS `faq_settings_blocks_hero_background_image_idx` ON `faq_settings_blocks_hero` (`background_image_id`)",
  "CREATE TABLE IF NOT EXISTS `faq_settings_blocks_rich_text` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `content` text NOT NULL, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `faq_settings`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `faq_settings_blocks_rich_text_order_idx` ON `faq_settings_blocks_rich_text` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `faq_settings_blocks_rich_text_parent_id_idx` ON `faq_settings_blocks_rich_text` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `faq_settings_blocks_rich_text_path_idx` ON `faq_settings_blocks_rich_text` (`_path`)",
  "CREATE TABLE IF NOT EXISTS `faq_settings_blocks_image_text` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `image_id` integer NOT NULL, `content` text NOT NULL, `image_side` text DEFAULT 'left', `block_name` text, FOREIGN KEY (`image_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null, FOREIGN KEY (`_parent_id`) REFERENCES `faq_settings`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `faq_settings_blocks_image_text_order_idx` ON `faq_settings_blocks_image_text` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `faq_settings_blocks_image_text_parent_id_idx` ON `faq_settings_blocks_image_text` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `faq_settings_blocks_image_text_path_idx` ON `faq_settings_blocks_image_text` (`_path`)",
  "CREATE INDEX IF NOT EXISTS `faq_settings_blocks_image_text_image_idx` ON `faq_settings_blocks_image_text` (`image_id`)",
  "CREATE TABLE IF NOT EXISTS `faq_settings_blocks_product_grid` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `heading` text, `category` text, `limit` numeric DEFAULT 4, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `faq_settings`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `faq_settings_blocks_product_grid_order_idx` ON `faq_settings_blocks_product_grid` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `faq_settings_blocks_product_grid_parent_id_idx` ON `faq_settings_blocks_product_grid` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `faq_settings_blocks_product_grid_path_idx` ON `faq_settings_blocks_product_grid` (`_path`)",
  "CREATE TABLE IF NOT EXISTS `faq_settings_blocks_event_grid` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `heading` text, `show_past` integer DEFAULT false, `limit` numeric DEFAULT 3, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `faq_settings`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `faq_settings_blocks_event_grid_order_idx` ON `faq_settings_blocks_event_grid` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `faq_settings_blocks_event_grid_parent_id_idx` ON `faq_settings_blocks_event_grid` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `faq_settings_blocks_event_grid_path_idx` ON `faq_settings_blocks_event_grid` (`_path`)",
  "CREATE TABLE IF NOT EXISTS `faq_settings_blocks_gallery` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `heading` text, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `faq_settings`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `faq_settings_blocks_gallery_order_idx` ON `faq_settings_blocks_gallery` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `faq_settings_blocks_gallery_parent_id_idx` ON `faq_settings_blocks_gallery` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `faq_settings_blocks_gallery_path_idx` ON `faq_settings_blocks_gallery` (`_path`)",
  "CREATE TABLE IF NOT EXISTS `faq_settings_blocks_faq` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `heading` text DEFAULT 'Frequently asked questions', `source` text DEFAULT 'category', `category` text, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `faq_settings`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `faq_settings_blocks_faq_order_idx` ON `faq_settings_blocks_faq` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `faq_settings_blocks_faq_parent_id_idx` ON `faq_settings_blocks_faq` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `faq_settings_blocks_faq_path_idx` ON `faq_settings_blocks_faq` (`_path`)",
  "CREATE TABLE IF NOT EXISTS `faq_settings_blocks_cta_banner` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `heading` text NOT NULL, `text` text, `button_label` text, `button_url` text, `style` text DEFAULT 'dark', `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `faq_settings`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `faq_settings_blocks_cta_banner_order_idx` ON `faq_settings_blocks_cta_banner` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `faq_settings_blocks_cta_banner_parent_id_idx` ON `faq_settings_blocks_cta_banner` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `faq_settings_blocks_cta_banner_path_idx` ON `faq_settings_blocks_cta_banner` (`_path`)",
  "CREATE TABLE IF NOT EXISTS `faq_settings_rels` ( `id` integer PRIMARY KEY NOT NULL, `order` integer, `parent_id` integer NOT NULL, `path` text NOT NULL, `media_id` integer, `faqs_id` integer, FOREIGN KEY (`parent_id`) REFERENCES `faq_settings`(`id`) ON UPDATE no action ON DELETE cascade, FOREIGN KEY (`media_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE cascade, FOREIGN KEY (`faqs_id`) REFERENCES `faqs`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `faq_settings_rels_order_idx` ON `faq_settings_rels` (`order`)",
  "CREATE INDEX IF NOT EXISTS `faq_settings_rels_parent_idx` ON `faq_settings_rels` (`parent_id`)",
  "CREATE INDEX IF NOT EXISTS `faq_settings_rels_path_idx` ON `faq_settings_rels` (`path`)",
  "CREATE INDEX IF NOT EXISTS `faq_settings_rels_media_id_idx` ON `faq_settings_rels` (`media_id`)",
  "CREATE INDEX IF NOT EXISTS `faq_settings_rels_faqs_id_idx` ON `faq_settings_rels` (`faqs_id`)",
  "CREATE TABLE IF NOT EXISTS `shop_settings_blocks_hero` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `heading` text NOT NULL, `subheading` text, `background_image_id` integer, `primary_cta_label` text, `primary_cta_url` text, `secondary_cta_label` text, `secondary_cta_url` text, `block_name` text, FOREIGN KEY (`background_image_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null, FOREIGN KEY (`_parent_id`) REFERENCES `shop_settings`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `shop_settings_blocks_hero_order_idx` ON `shop_settings_blocks_hero` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `shop_settings_blocks_hero_parent_id_idx` ON `shop_settings_blocks_hero` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `shop_settings_blocks_hero_path_idx` ON `shop_settings_blocks_hero` (`_path`)",
  "CREATE INDEX IF NOT EXISTS `shop_settings_blocks_hero_background_image_idx` ON `shop_settings_blocks_hero` (`background_image_id`)",
  "CREATE TABLE IF NOT EXISTS `shop_settings_blocks_rich_text` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `content` text NOT NULL, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `shop_settings`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `shop_settings_blocks_rich_text_order_idx` ON `shop_settings_blocks_rich_text` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `shop_settings_blocks_rich_text_parent_id_idx` ON `shop_settings_blocks_rich_text` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `shop_settings_blocks_rich_text_path_idx` ON `shop_settings_blocks_rich_text` (`_path`)",
  "CREATE TABLE IF NOT EXISTS `shop_settings_blocks_image_text` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `image_id` integer NOT NULL, `content` text NOT NULL, `image_side` text DEFAULT 'left', `block_name` text, FOREIGN KEY (`image_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null, FOREIGN KEY (`_parent_id`) REFERENCES `shop_settings`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `shop_settings_blocks_image_text_order_idx` ON `shop_settings_blocks_image_text` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `shop_settings_blocks_image_text_parent_id_idx` ON `shop_settings_blocks_image_text` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `shop_settings_blocks_image_text_path_idx` ON `shop_settings_blocks_image_text` (`_path`)",
  "CREATE INDEX IF NOT EXISTS `shop_settings_blocks_image_text_image_idx` ON `shop_settings_blocks_image_text` (`image_id`)",
  "CREATE TABLE IF NOT EXISTS `shop_settings_blocks_product_grid` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `heading` text, `category` text, `limit` numeric DEFAULT 4, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `shop_settings`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `shop_settings_blocks_product_grid_order_idx` ON `shop_settings_blocks_product_grid` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `shop_settings_blocks_product_grid_parent_id_idx` ON `shop_settings_blocks_product_grid` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `shop_settings_blocks_product_grid_path_idx` ON `shop_settings_blocks_product_grid` (`_path`)",
  "CREATE TABLE IF NOT EXISTS `shop_settings_blocks_event_grid` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `heading` text, `show_past` integer DEFAULT false, `limit` numeric DEFAULT 3, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `shop_settings`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `shop_settings_blocks_event_grid_order_idx` ON `shop_settings_blocks_event_grid` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `shop_settings_blocks_event_grid_parent_id_idx` ON `shop_settings_blocks_event_grid` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `shop_settings_blocks_event_grid_path_idx` ON `shop_settings_blocks_event_grid` (`_path`)",
  "CREATE TABLE IF NOT EXISTS `shop_settings_blocks_gallery` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `heading` text, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `shop_settings`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `shop_settings_blocks_gallery_order_idx` ON `shop_settings_blocks_gallery` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `shop_settings_blocks_gallery_parent_id_idx` ON `shop_settings_blocks_gallery` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `shop_settings_blocks_gallery_path_idx` ON `shop_settings_blocks_gallery` (`_path`)",
  "CREATE TABLE IF NOT EXISTS `shop_settings_blocks_faq` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `heading` text DEFAULT 'Frequently asked questions', `source` text DEFAULT 'category', `category` text, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `shop_settings`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `shop_settings_blocks_faq_order_idx` ON `shop_settings_blocks_faq` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `shop_settings_blocks_faq_parent_id_idx` ON `shop_settings_blocks_faq` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `shop_settings_blocks_faq_path_idx` ON `shop_settings_blocks_faq` (`_path`)",
  "CREATE TABLE IF NOT EXISTS `shop_settings_blocks_cta_banner` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `heading` text NOT NULL, `text` text, `button_label` text, `button_url` text, `style` text DEFAULT 'dark', `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `shop_settings`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `shop_settings_blocks_cta_banner_order_idx` ON `shop_settings_blocks_cta_banner` (`_order`)",
  "CREATE INDEX IF NOT EXISTS `shop_settings_blocks_cta_banner_parent_id_idx` ON `shop_settings_blocks_cta_banner` (`_parent_id`)",
  "CREATE INDEX IF NOT EXISTS `shop_settings_blocks_cta_banner_path_idx` ON `shop_settings_blocks_cta_banner` (`_path`)",
  "CREATE TABLE IF NOT EXISTS `shop_settings_rels` ( `id` integer PRIMARY KEY NOT NULL, `order` integer, `parent_id` integer NOT NULL, `path` text NOT NULL, `media_id` integer, `faqs_id` integer, FOREIGN KEY (`parent_id`) REFERENCES `shop_settings`(`id`) ON UPDATE no action ON DELETE cascade, FOREIGN KEY (`media_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE cascade, FOREIGN KEY (`faqs_id`) REFERENCES `faqs`(`id`) ON UPDATE no action ON DELETE cascade )",
  "CREATE INDEX IF NOT EXISTS `shop_settings_rels_order_idx` ON `shop_settings_rels` (`order`)",
  "CREATE INDEX IF NOT EXISTS `shop_settings_rels_parent_idx` ON `shop_settings_rels` (`parent_id`)",
  "CREATE INDEX IF NOT EXISTS `shop_settings_rels_path_idx` ON `shop_settings_rels` (`path`)",
  "CREATE INDEX IF NOT EXISTS `shop_settings_rels_media_id_idx` ON `shop_settings_rels` (`media_id`)",
  "CREATE INDEX IF NOT EXISTS `shop_settings_rels_faqs_id_idx` ON `shop_settings_rels` (`faqs_id`)"
]
