/**
 * Schema additions for the page-builder upgrade: Section and Loop blocks, the
 * per-block `design` settings, and Field Groups (custom fields).
 *
 * GENERATED, then committed - do not hand-edit. Produced by diffing the schema
 * the CMS config wants against the schema production actually has, so it contains only
 * additions: 24 new tables, 90 new columns, 79 new indexes, and nothing
 * destructive.
 *
 * This exists as data rather than a .sql file because the CLI's `migrate` cannot
 * reach production D1 from this CI environment (see the note on the D1 binding
 * in wrangler.jsonc), and `ALTER TABLE ADD COLUMN` has no `IF NOT EXISTS` form
 * in SQLite - so a plain SQL file could not safely be re-run on every deploy.
 * The /api/internal-migrate route applies these against the live D1 binding,
 * checking PRAGMA table_info before each column add, which makes the whole
 * thing idempotent by construction.
 */

export type SchemaTable = { table: string; sql: string }
export type SchemaColumn = { table: string; column: string; sql: string }
export type SchemaIndex = { index: string; sql: string }

export const NEW_TABLES: SchemaTable[] = [
  { table: "_pages_v_blocks_loop", sql: "CREATE TABLE IF NOT EXISTS `_pages_v_blocks_loop` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` integer PRIMARY KEY NOT NULL, `heading` text, `template_id` integer, `source` text DEFAULT 'products', `category` text, `limit` numeric DEFAULT 6, `columns` numeric DEFAULT 3, `sort_by` text DEFAULT 'newest', `design` text, `_uuid` text, `block_name` text, FOREIGN KEY (`template_id`) REFERENCES `page_templates`(`id`) ON UPDATE no action ON DELETE set null, FOREIGN KEY (`_parent_id`) REFERENCES `_pages_v`(`id`) ON UPDATE no action ON DELETE cascade )" },
  { table: "_pages_v_blocks_section", sql: "CREATE TABLE IF NOT EXISTS `_pages_v_blocks_section` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` integer PRIMARY KEY NOT NULL, `columns` text, `design` text, `_uuid` text, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `_pages_v`(`id`) ON UPDATE no action ON DELETE cascade )" },
  { table: "_posts_v_blocks_loop", sql: "CREATE TABLE IF NOT EXISTS `_posts_v_blocks_loop` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` integer PRIMARY KEY NOT NULL, `heading` text, `template_id` integer, `source` text DEFAULT 'products', `category` text, `limit` numeric DEFAULT 6, `columns` numeric DEFAULT 3, `sort_by` text DEFAULT 'newest', `design` text, `_uuid` text, `block_name` text, FOREIGN KEY (`template_id`) REFERENCES `page_templates`(`id`) ON UPDATE no action ON DELETE set null, FOREIGN KEY (`_parent_id`) REFERENCES `_posts_v`(`id`) ON UPDATE no action ON DELETE cascade )" },
  { table: "_posts_v_blocks_section", sql: "CREATE TABLE IF NOT EXISTS `_posts_v_blocks_section` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` integer PRIMARY KEY NOT NULL, `columns` text, `design` text, `_uuid` text, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `_posts_v`(`id`) ON UPDATE no action ON DELETE cascade )" },
  { table: "_products_v_blocks_loop", sql: "CREATE TABLE IF NOT EXISTS `_products_v_blocks_loop` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` integer PRIMARY KEY NOT NULL, `heading` text, `template_id` integer, `source` text DEFAULT 'products', `category` text, `limit` numeric DEFAULT 6, `columns` numeric DEFAULT 3, `sort_by` text DEFAULT 'newest', `design` text, `_uuid` text, `block_name` text, FOREIGN KEY (`template_id`) REFERENCES `page_templates`(`id`) ON UPDATE no action ON DELETE set null, FOREIGN KEY (`_parent_id`) REFERENCES `_products_v`(`id`) ON UPDATE no action ON DELETE cascade )" },
  { table: "_products_v_blocks_section", sql: "CREATE TABLE IF NOT EXISTS `_products_v_blocks_section` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` integer PRIMARY KEY NOT NULL, `columns` text, `design` text, `_uuid` text, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `_products_v`(`id`) ON UPDATE no action ON DELETE cascade )" },
  { table: "blog_settings_blocks_loop", sql: "CREATE TABLE IF NOT EXISTS `blog_settings_blocks_loop` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `heading` text, `template_id` integer NOT NULL, `source` text DEFAULT 'products', `category` text, `limit` numeric DEFAULT 6, `columns` numeric DEFAULT 3, `sort_by` text DEFAULT 'newest', `design` text, `block_name` text, FOREIGN KEY (`template_id`) REFERENCES `page_templates`(`id`) ON UPDATE no action ON DELETE set null, FOREIGN KEY (`_parent_id`) REFERENCES `blog_settings`(`id`) ON UPDATE no action ON DELETE cascade )" },
  { table: "blog_settings_blocks_section", sql: "CREATE TABLE IF NOT EXISTS `blog_settings_blocks_section` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `columns` text, `design` text, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `blog_settings`(`id`) ON UPDATE no action ON DELETE cascade )" },
  { table: "faq_settings_blocks_loop", sql: "CREATE TABLE IF NOT EXISTS `faq_settings_blocks_loop` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `heading` text, `template_id` integer NOT NULL, `source` text DEFAULT 'products', `category` text, `limit` numeric DEFAULT 6, `columns` numeric DEFAULT 3, `sort_by` text DEFAULT 'newest', `design` text, `block_name` text, FOREIGN KEY (`template_id`) REFERENCES `page_templates`(`id`) ON UPDATE no action ON DELETE set null, FOREIGN KEY (`_parent_id`) REFERENCES `faq_settings`(`id`) ON UPDATE no action ON DELETE cascade )" },
  { table: "faq_settings_blocks_section", sql: "CREATE TABLE IF NOT EXISTS `faq_settings_blocks_section` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `columns` text, `design` text, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `faq_settings`(`id`) ON UPDATE no action ON DELETE cascade )" },
  { table: "field_groups", sql: "CREATE TABLE IF NOT EXISTS `field_groups` ( `id` integer PRIMARY KEY NOT NULL, `name` text NOT NULL, `description` text, `updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL, `created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL )" },
  { table: "field_groups_fields", sql: "CREATE TABLE IF NOT EXISTS `field_groups_fields` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `id` text PRIMARY KEY NOT NULL, `label` text NOT NULL, `name` text NOT NULL, `type` text DEFAULT 'text' NOT NULL, `required` integer DEFAULT false, `help_text` text, `default_value` text, FOREIGN KEY (`_parent_id`) REFERENCES `field_groups`(`id`) ON UPDATE no action ON DELETE cascade )" },
  { table: "field_groups_fields_options", sql: "CREATE TABLE IF NOT EXISTS `field_groups_fields_options` ( `_order` integer NOT NULL, `_parent_id` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `label` text, `value` text, FOREIGN KEY (`_parent_id`) REFERENCES `field_groups_fields`(`id`) ON UPDATE no action ON DELETE cascade )" },
  { table: "field_groups_target_collections", sql: "CREATE TABLE IF NOT EXISTS `field_groups_target_collections` ( `order` integer NOT NULL, `parent_id` integer NOT NULL, `value` text, `id` integer PRIMARY KEY NOT NULL, FOREIGN KEY (`parent_id`) REFERENCES `field_groups`(`id`) ON UPDATE no action ON DELETE cascade )" },
  { table: "page_templates_blocks_loop", sql: "CREATE TABLE IF NOT EXISTS `page_templates_blocks_loop` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `heading` text, `template_id` integer NOT NULL, `source` text DEFAULT 'products', `category` text, `limit` numeric DEFAULT 6, `columns` numeric DEFAULT 3, `sort_by` text DEFAULT 'newest', `design` text, `block_name` text, FOREIGN KEY (`template_id`) REFERENCES `page_templates`(`id`) ON UPDATE no action ON DELETE set null, FOREIGN KEY (`_parent_id`) REFERENCES `page_templates`(`id`) ON UPDATE no action ON DELETE cascade )" },
  { table: "page_templates_blocks_section", sql: "CREATE TABLE IF NOT EXISTS `page_templates_blocks_section` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `columns` text, `design` text, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `page_templates`(`id`) ON UPDATE no action ON DELETE cascade )" },
  { table: "pages_blocks_loop", sql: "CREATE TABLE IF NOT EXISTS `pages_blocks_loop` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `heading` text, `template_id` integer, `source` text DEFAULT 'products', `category` text, `limit` numeric DEFAULT 6, `columns` numeric DEFAULT 3, `sort_by` text DEFAULT 'newest', `design` text, `block_name` text, FOREIGN KEY (`template_id`) REFERENCES `page_templates`(`id`) ON UPDATE no action ON DELETE set null, FOREIGN KEY (`_parent_id`) REFERENCES `pages`(`id`) ON UPDATE no action ON DELETE cascade )" },
  { table: "pages_blocks_section", sql: "CREATE TABLE IF NOT EXISTS `pages_blocks_section` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `columns` text, `design` text, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `pages`(`id`) ON UPDATE no action ON DELETE cascade )" },
  { table: "posts_blocks_loop", sql: "CREATE TABLE IF NOT EXISTS `posts_blocks_loop` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `heading` text, `template_id` integer, `source` text DEFAULT 'products', `category` text, `limit` numeric DEFAULT 6, `columns` numeric DEFAULT 3, `sort_by` text DEFAULT 'newest', `design` text, `block_name` text, FOREIGN KEY (`template_id`) REFERENCES `page_templates`(`id`) ON UPDATE no action ON DELETE set null, FOREIGN KEY (`_parent_id`) REFERENCES `posts`(`id`) ON UPDATE no action ON DELETE cascade )" },
  { table: "posts_blocks_section", sql: "CREATE TABLE IF NOT EXISTS `posts_blocks_section` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `columns` text, `design` text, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `posts`(`id`) ON UPDATE no action ON DELETE cascade )" },
  { table: "products_blocks_loop", sql: "CREATE TABLE IF NOT EXISTS `products_blocks_loop` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `heading` text, `template_id` integer, `source` text DEFAULT 'products', `category` text, `limit` numeric DEFAULT 6, `columns` numeric DEFAULT 3, `sort_by` text DEFAULT 'newest', `design` text, `block_name` text, FOREIGN KEY (`template_id`) REFERENCES `page_templates`(`id`) ON UPDATE no action ON DELETE set null, FOREIGN KEY (`_parent_id`) REFERENCES `products`(`id`) ON UPDATE no action ON DELETE cascade )" },
  { table: "products_blocks_section", sql: "CREATE TABLE IF NOT EXISTS `products_blocks_section` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `columns` text, `design` text, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `products`(`id`) ON UPDATE no action ON DELETE cascade )" },
  { table: "shop_settings_blocks_loop", sql: "CREATE TABLE IF NOT EXISTS `shop_settings_blocks_loop` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `heading` text, `template_id` integer NOT NULL, `source` text DEFAULT 'products', `category` text, `limit` numeric DEFAULT 6, `columns` numeric DEFAULT 3, `sort_by` text DEFAULT 'newest', `design` text, `block_name` text, FOREIGN KEY (`template_id`) REFERENCES `page_templates`(`id`) ON UPDATE no action ON DELETE set null, FOREIGN KEY (`_parent_id`) REFERENCES `shop_settings`(`id`) ON UPDATE no action ON DELETE cascade )" },
  { table: "shop_settings_blocks_section", sql: "CREATE TABLE IF NOT EXISTS `shop_settings_blocks_section` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `_path` text NOT NULL, `id` text PRIMARY KEY NOT NULL, `columns` text, `design` text, `block_name` text, FOREIGN KEY (`_parent_id`) REFERENCES `shop_settings`(`id`) ON UPDATE no action ON DELETE cascade )" },
]

export const NEW_COLUMNS: SchemaColumn[] = [
  { table: "_events_v", column: "version_custom_fields", sql: "ALTER TABLE `_events_v` ADD `version_custom_fields` TEXT" },
  { table: "_pages_v", column: "version_custom_fields", sql: "ALTER TABLE `_pages_v` ADD `version_custom_fields` TEXT" },
  { table: "_pages_v_blocks_cta_banner", column: "design", sql: "ALTER TABLE `_pages_v_blocks_cta_banner` ADD `design` TEXT" },
  { table: "_pages_v_blocks_event_grid", column: "design", sql: "ALTER TABLE `_pages_v_blocks_event_grid` ADD `design` TEXT" },
  { table: "_pages_v_blocks_faq", column: "design", sql: "ALTER TABLE `_pages_v_blocks_faq` ADD `design` TEXT" },
  { table: "_pages_v_blocks_gallery", column: "design", sql: "ALTER TABLE `_pages_v_blocks_gallery` ADD `design` TEXT" },
  { table: "_pages_v_blocks_hero", column: "design", sql: "ALTER TABLE `_pages_v_blocks_hero` ADD `design` TEXT" },
  { table: "_pages_v_blocks_image_text", column: "design", sql: "ALTER TABLE `_pages_v_blocks_image_text` ADD `design` TEXT" },
  { table: "_pages_v_blocks_product_grid", column: "design", sql: "ALTER TABLE `_pages_v_blocks_product_grid` ADD `design` TEXT" },
  { table: "_pages_v_blocks_rich_text", column: "design", sql: "ALTER TABLE `_pages_v_blocks_rich_text` ADD `design` TEXT" },
  { table: "_posts_v", column: "version_custom_fields", sql: "ALTER TABLE `_posts_v` ADD `version_custom_fields` TEXT" },
  { table: "_posts_v_blocks_cta_banner", column: "design", sql: "ALTER TABLE `_posts_v_blocks_cta_banner` ADD `design` TEXT" },
  { table: "_posts_v_blocks_event_grid", column: "design", sql: "ALTER TABLE `_posts_v_blocks_event_grid` ADD `design` TEXT" },
  { table: "_posts_v_blocks_faq", column: "design", sql: "ALTER TABLE `_posts_v_blocks_faq` ADD `design` TEXT" },
  { table: "_posts_v_blocks_gallery", column: "design", sql: "ALTER TABLE `_posts_v_blocks_gallery` ADD `design` TEXT" },
  { table: "_posts_v_blocks_hero", column: "design", sql: "ALTER TABLE `_posts_v_blocks_hero` ADD `design` TEXT" },
  { table: "_posts_v_blocks_image_text", column: "design", sql: "ALTER TABLE `_posts_v_blocks_image_text` ADD `design` TEXT" },
  { table: "_posts_v_blocks_product_grid", column: "design", sql: "ALTER TABLE `_posts_v_blocks_product_grid` ADD `design` TEXT" },
  { table: "_posts_v_blocks_rich_text", column: "design", sql: "ALTER TABLE `_posts_v_blocks_rich_text` ADD `design` TEXT" },
  { table: "_products_v", column: "version_custom_fields", sql: "ALTER TABLE `_products_v` ADD `version_custom_fields` TEXT" },
  { table: "_products_v_blocks_cta_banner", column: "design", sql: "ALTER TABLE `_products_v_blocks_cta_banner` ADD `design` TEXT" },
  { table: "_products_v_blocks_event_grid", column: "design", sql: "ALTER TABLE `_products_v_blocks_event_grid` ADD `design` TEXT" },
  { table: "_products_v_blocks_faq", column: "design", sql: "ALTER TABLE `_products_v_blocks_faq` ADD `design` TEXT" },
  { table: "_products_v_blocks_gallery", column: "design", sql: "ALTER TABLE `_products_v_blocks_gallery` ADD `design` TEXT" },
  { table: "_products_v_blocks_hero", column: "design", sql: "ALTER TABLE `_products_v_blocks_hero` ADD `design` TEXT" },
  { table: "_products_v_blocks_image_text", column: "design", sql: "ALTER TABLE `_products_v_blocks_image_text` ADD `design` TEXT" },
  { table: "_products_v_blocks_product_grid", column: "design", sql: "ALTER TABLE `_products_v_blocks_product_grid` ADD `design` TEXT" },
  { table: "_products_v_blocks_rich_text", column: "design", sql: "ALTER TABLE `_products_v_blocks_rich_text` ADD `design` TEXT" },
  { table: "blog_settings_blocks_cta_banner", column: "design", sql: "ALTER TABLE `blog_settings_blocks_cta_banner` ADD `design` TEXT" },
  { table: "blog_settings_blocks_event_grid", column: "design", sql: "ALTER TABLE `blog_settings_blocks_event_grid` ADD `design` TEXT" },
  { table: "blog_settings_blocks_faq", column: "design", sql: "ALTER TABLE `blog_settings_blocks_faq` ADD `design` TEXT" },
  { table: "blog_settings_blocks_gallery", column: "design", sql: "ALTER TABLE `blog_settings_blocks_gallery` ADD `design` TEXT" },
  { table: "blog_settings_blocks_hero", column: "design", sql: "ALTER TABLE `blog_settings_blocks_hero` ADD `design` TEXT" },
  { table: "blog_settings_blocks_image_text", column: "design", sql: "ALTER TABLE `blog_settings_blocks_image_text` ADD `design` TEXT" },
  { table: "blog_settings_blocks_product_grid", column: "design", sql: "ALTER TABLE `blog_settings_blocks_product_grid` ADD `design` TEXT" },
  { table: "blog_settings_blocks_rich_text", column: "design", sql: "ALTER TABLE `blog_settings_blocks_rich_text` ADD `design` TEXT" },
  { table: "events", column: "custom_fields", sql: "ALTER TABLE `events` ADD `custom_fields` TEXT" },
  { table: "faq_settings_blocks_cta_banner", column: "design", sql: "ALTER TABLE `faq_settings_blocks_cta_banner` ADD `design` TEXT" },
  { table: "faq_settings_blocks_event_grid", column: "design", sql: "ALTER TABLE `faq_settings_blocks_event_grid` ADD `design` TEXT" },
  { table: "faq_settings_blocks_faq", column: "design", sql: "ALTER TABLE `faq_settings_blocks_faq` ADD `design` TEXT" },
  { table: "faq_settings_blocks_gallery", column: "design", sql: "ALTER TABLE `faq_settings_blocks_gallery` ADD `design` TEXT" },
  { table: "faq_settings_blocks_hero", column: "design", sql: "ALTER TABLE `faq_settings_blocks_hero` ADD `design` TEXT" },
  { table: "faq_settings_blocks_image_text", column: "design", sql: "ALTER TABLE `faq_settings_blocks_image_text` ADD `design` TEXT" },
  { table: "faq_settings_blocks_product_grid", column: "design", sql: "ALTER TABLE `faq_settings_blocks_product_grid` ADD `design` TEXT" },
  { table: "faq_settings_blocks_rich_text", column: "design", sql: "ALTER TABLE `faq_settings_blocks_rich_text` ADD `design` TEXT" },
  { table: "faqs", column: "custom_fields", sql: "ALTER TABLE `faqs` ADD `custom_fields` TEXT" },
  { table: "page_templates_blocks_cta_banner", column: "design", sql: "ALTER TABLE `page_templates_blocks_cta_banner` ADD `design` TEXT" },
  { table: "page_templates_blocks_event_grid", column: "design", sql: "ALTER TABLE `page_templates_blocks_event_grid` ADD `design` TEXT" },
  { table: "page_templates_blocks_faq", column: "design", sql: "ALTER TABLE `page_templates_blocks_faq` ADD `design` TEXT" },
  { table: "page_templates_blocks_gallery", column: "design", sql: "ALTER TABLE `page_templates_blocks_gallery` ADD `design` TEXT" },
  { table: "page_templates_blocks_hero", column: "design", sql: "ALTER TABLE `page_templates_blocks_hero` ADD `design` TEXT" },
  { table: "page_templates_blocks_image_text", column: "design", sql: "ALTER TABLE `page_templates_blocks_image_text` ADD `design` TEXT" },
  { table: "page_templates_blocks_product_grid", column: "design", sql: "ALTER TABLE `page_templates_blocks_product_grid` ADD `design` TEXT" },
  { table: "page_templates_blocks_rich_text", column: "design", sql: "ALTER TABLE `page_templates_blocks_rich_text` ADD `design` TEXT" },
  { table: "pages", column: "custom_fields", sql: "ALTER TABLE `pages` ADD `custom_fields` TEXT" },
  { table: "pages_blocks_cta_banner", column: "design", sql: "ALTER TABLE `pages_blocks_cta_banner` ADD `design` TEXT" },
  { table: "pages_blocks_event_grid", column: "design", sql: "ALTER TABLE `pages_blocks_event_grid` ADD `design` TEXT" },
  { table: "pages_blocks_faq", column: "design", sql: "ALTER TABLE `pages_blocks_faq` ADD `design` TEXT" },
  { table: "pages_blocks_gallery", column: "design", sql: "ALTER TABLE `pages_blocks_gallery` ADD `design` TEXT" },
  { table: "pages_blocks_hero", column: "design", sql: "ALTER TABLE `pages_blocks_hero` ADD `design` TEXT" },
  { table: "pages_blocks_image_text", column: "design", sql: "ALTER TABLE `pages_blocks_image_text` ADD `design` TEXT" },
  { table: "pages_blocks_product_grid", column: "design", sql: "ALTER TABLE `pages_blocks_product_grid` ADD `design` TEXT" },
  { table: "pages_blocks_rich_text", column: "design", sql: "ALTER TABLE `pages_blocks_rich_text` ADD `design` TEXT" },
  { table: "payload_locked_documents_rels", column: "field_groups_id", sql: "ALTER TABLE `payload_locked_documents_rels` ADD `field_groups_id` INTEGER" },
  { table: "posts", column: "custom_fields", sql: "ALTER TABLE `posts` ADD `custom_fields` TEXT" },
  { table: "posts_blocks_cta_banner", column: "design", sql: "ALTER TABLE `posts_blocks_cta_banner` ADD `design` TEXT" },
  { table: "posts_blocks_event_grid", column: "design", sql: "ALTER TABLE `posts_blocks_event_grid` ADD `design` TEXT" },
  { table: "posts_blocks_faq", column: "design", sql: "ALTER TABLE `posts_blocks_faq` ADD `design` TEXT" },
  { table: "posts_blocks_gallery", column: "design", sql: "ALTER TABLE `posts_blocks_gallery` ADD `design` TEXT" },
  { table: "posts_blocks_hero", column: "design", sql: "ALTER TABLE `posts_blocks_hero` ADD `design` TEXT" },
  { table: "posts_blocks_image_text", column: "design", sql: "ALTER TABLE `posts_blocks_image_text` ADD `design` TEXT" },
  { table: "posts_blocks_product_grid", column: "design", sql: "ALTER TABLE `posts_blocks_product_grid` ADD `design` TEXT" },
  { table: "posts_blocks_rich_text", column: "design", sql: "ALTER TABLE `posts_blocks_rich_text` ADD `design` TEXT" },
  { table: "products", column: "custom_fields", sql: "ALTER TABLE `products` ADD `custom_fields` TEXT" },
  { table: "products_blocks_cta_banner", column: "design", sql: "ALTER TABLE `products_blocks_cta_banner` ADD `design` TEXT" },
  { table: "products_blocks_event_grid", column: "design", sql: "ALTER TABLE `products_blocks_event_grid` ADD `design` TEXT" },
  { table: "products_blocks_faq", column: "design", sql: "ALTER TABLE `products_blocks_faq` ADD `design` TEXT" },
  { table: "products_blocks_gallery", column: "design", sql: "ALTER TABLE `products_blocks_gallery` ADD `design` TEXT" },
  { table: "products_blocks_hero", column: "design", sql: "ALTER TABLE `products_blocks_hero` ADD `design` TEXT" },
  { table: "products_blocks_image_text", column: "design", sql: "ALTER TABLE `products_blocks_image_text` ADD `design` TEXT" },
  { table: "products_blocks_product_grid", column: "design", sql: "ALTER TABLE `products_blocks_product_grid` ADD `design` TEXT" },
  { table: "products_blocks_rich_text", column: "design", sql: "ALTER TABLE `products_blocks_rich_text` ADD `design` TEXT" },
  { table: "shop_settings_blocks_cta_banner", column: "design", sql: "ALTER TABLE `shop_settings_blocks_cta_banner` ADD `design` TEXT" },
  { table: "shop_settings_blocks_event_grid", column: "design", sql: "ALTER TABLE `shop_settings_blocks_event_grid` ADD `design` TEXT" },
  { table: "shop_settings_blocks_faq", column: "design", sql: "ALTER TABLE `shop_settings_blocks_faq` ADD `design` TEXT" },
  { table: "shop_settings_blocks_gallery", column: "design", sql: "ALTER TABLE `shop_settings_blocks_gallery` ADD `design` TEXT" },
  { table: "shop_settings_blocks_hero", column: "design", sql: "ALTER TABLE `shop_settings_blocks_hero` ADD `design` TEXT" },
  { table: "shop_settings_blocks_image_text", column: "design", sql: "ALTER TABLE `shop_settings_blocks_image_text` ADD `design` TEXT" },
  { table: "shop_settings_blocks_product_grid", column: "design", sql: "ALTER TABLE `shop_settings_blocks_product_grid` ADD `design` TEXT" },
  { table: "shop_settings_blocks_rich_text", column: "design", sql: "ALTER TABLE `shop_settings_blocks_rich_text` ADD `design` TEXT" },
]

export const NEW_INDEXES: SchemaIndex[] = [
  { index: "_pages_v_blocks_loop_order_idx", sql: "CREATE INDEX IF NOT EXISTS `_pages_v_blocks_loop_order_idx` ON `_pages_v_blocks_loop` (`_order`)" },
  { index: "_pages_v_blocks_loop_parent_id_idx", sql: "CREATE INDEX IF NOT EXISTS `_pages_v_blocks_loop_parent_id_idx` ON `_pages_v_blocks_loop` (`_parent_id`)" },
  { index: "_pages_v_blocks_loop_path_idx", sql: "CREATE INDEX IF NOT EXISTS `_pages_v_blocks_loop_path_idx` ON `_pages_v_blocks_loop` (`_path`)" },
  { index: "_pages_v_blocks_loop_template_idx", sql: "CREATE INDEX IF NOT EXISTS `_pages_v_blocks_loop_template_idx` ON `_pages_v_blocks_loop` (`template_id`)" },
  { index: "_pages_v_blocks_section_order_idx", sql: "CREATE INDEX IF NOT EXISTS `_pages_v_blocks_section_order_idx` ON `_pages_v_blocks_section` (`_order`)" },
  { index: "_pages_v_blocks_section_parent_id_idx", sql: "CREATE INDEX IF NOT EXISTS `_pages_v_blocks_section_parent_id_idx` ON `_pages_v_blocks_section` (`_parent_id`)" },
  { index: "_pages_v_blocks_section_path_idx", sql: "CREATE INDEX IF NOT EXISTS `_pages_v_blocks_section_path_idx` ON `_pages_v_blocks_section` (`_path`)" },
  { index: "_posts_v_blocks_loop_order_idx", sql: "CREATE INDEX IF NOT EXISTS `_posts_v_blocks_loop_order_idx` ON `_posts_v_blocks_loop` (`_order`)" },
  { index: "_posts_v_blocks_loop_parent_id_idx", sql: "CREATE INDEX IF NOT EXISTS `_posts_v_blocks_loop_parent_id_idx` ON `_posts_v_blocks_loop` (`_parent_id`)" },
  { index: "_posts_v_blocks_loop_path_idx", sql: "CREATE INDEX IF NOT EXISTS `_posts_v_blocks_loop_path_idx` ON `_posts_v_blocks_loop` (`_path`)" },
  { index: "_posts_v_blocks_loop_template_idx", sql: "CREATE INDEX IF NOT EXISTS `_posts_v_blocks_loop_template_idx` ON `_posts_v_blocks_loop` (`template_id`)" },
  { index: "_posts_v_blocks_section_order_idx", sql: "CREATE INDEX IF NOT EXISTS `_posts_v_blocks_section_order_idx` ON `_posts_v_blocks_section` (`_order`)" },
  { index: "_posts_v_blocks_section_parent_id_idx", sql: "CREATE INDEX IF NOT EXISTS `_posts_v_blocks_section_parent_id_idx` ON `_posts_v_blocks_section` (`_parent_id`)" },
  { index: "_posts_v_blocks_section_path_idx", sql: "CREATE INDEX IF NOT EXISTS `_posts_v_blocks_section_path_idx` ON `_posts_v_blocks_section` (`_path`)" },
  { index: "_products_v_blocks_loop_order_idx", sql: "CREATE INDEX IF NOT EXISTS `_products_v_blocks_loop_order_idx` ON `_products_v_blocks_loop` (`_order`)" },
  { index: "_products_v_blocks_loop_parent_id_idx", sql: "CREATE INDEX IF NOT EXISTS `_products_v_blocks_loop_parent_id_idx` ON `_products_v_blocks_loop` (`_parent_id`)" },
  { index: "_products_v_blocks_loop_path_idx", sql: "CREATE INDEX IF NOT EXISTS `_products_v_blocks_loop_path_idx` ON `_products_v_blocks_loop` (`_path`)" },
  { index: "_products_v_blocks_loop_template_idx", sql: "CREATE INDEX IF NOT EXISTS `_products_v_blocks_loop_template_idx` ON `_products_v_blocks_loop` (`template_id`)" },
  { index: "_products_v_blocks_section_order_idx", sql: "CREATE INDEX IF NOT EXISTS `_products_v_blocks_section_order_idx` ON `_products_v_blocks_section` (`_order`)" },
  { index: "_products_v_blocks_section_parent_id_idx", sql: "CREATE INDEX IF NOT EXISTS `_products_v_blocks_section_parent_id_idx` ON `_products_v_blocks_section` (`_parent_id`)" },
  { index: "_products_v_blocks_section_path_idx", sql: "CREATE INDEX IF NOT EXISTS `_products_v_blocks_section_path_idx` ON `_products_v_blocks_section` (`_path`)" },
  { index: "blog_settings_blocks_loop_order_idx", sql: "CREATE INDEX IF NOT EXISTS `blog_settings_blocks_loop_order_idx` ON `blog_settings_blocks_loop` (`_order`)" },
  { index: "blog_settings_blocks_loop_parent_id_idx", sql: "CREATE INDEX IF NOT EXISTS `blog_settings_blocks_loop_parent_id_idx` ON `blog_settings_blocks_loop` (`_parent_id`)" },
  { index: "blog_settings_blocks_loop_path_idx", sql: "CREATE INDEX IF NOT EXISTS `blog_settings_blocks_loop_path_idx` ON `blog_settings_blocks_loop` (`_path`)" },
  { index: "blog_settings_blocks_loop_template_idx", sql: "CREATE INDEX IF NOT EXISTS `blog_settings_blocks_loop_template_idx` ON `blog_settings_blocks_loop` (`template_id`)" },
  { index: "blog_settings_blocks_section_order_idx", sql: "CREATE INDEX IF NOT EXISTS `blog_settings_blocks_section_order_idx` ON `blog_settings_blocks_section` (`_order`)" },
  { index: "blog_settings_blocks_section_parent_id_idx", sql: "CREATE INDEX IF NOT EXISTS `blog_settings_blocks_section_parent_id_idx` ON `blog_settings_blocks_section` (`_parent_id`)" },
  { index: "blog_settings_blocks_section_path_idx", sql: "CREATE INDEX IF NOT EXISTS `blog_settings_blocks_section_path_idx` ON `blog_settings_blocks_section` (`_path`)" },
  { index: "faq_settings_blocks_loop_order_idx", sql: "CREATE INDEX IF NOT EXISTS `faq_settings_blocks_loop_order_idx` ON `faq_settings_blocks_loop` (`_order`)" },
  { index: "faq_settings_blocks_loop_parent_id_idx", sql: "CREATE INDEX IF NOT EXISTS `faq_settings_blocks_loop_parent_id_idx` ON `faq_settings_blocks_loop` (`_parent_id`)" },
  { index: "faq_settings_blocks_loop_path_idx", sql: "CREATE INDEX IF NOT EXISTS `faq_settings_blocks_loop_path_idx` ON `faq_settings_blocks_loop` (`_path`)" },
  { index: "faq_settings_blocks_loop_template_idx", sql: "CREATE INDEX IF NOT EXISTS `faq_settings_blocks_loop_template_idx` ON `faq_settings_blocks_loop` (`template_id`)" },
  { index: "faq_settings_blocks_section_order_idx", sql: "CREATE INDEX IF NOT EXISTS `faq_settings_blocks_section_order_idx` ON `faq_settings_blocks_section` (`_order`)" },
  { index: "faq_settings_blocks_section_parent_id_idx", sql: "CREATE INDEX IF NOT EXISTS `faq_settings_blocks_section_parent_id_idx` ON `faq_settings_blocks_section` (`_parent_id`)" },
  { index: "faq_settings_blocks_section_path_idx", sql: "CREATE INDEX IF NOT EXISTS `faq_settings_blocks_section_path_idx` ON `faq_settings_blocks_section` (`_path`)" },
  { index: "field_groups_created_at_idx", sql: "CREATE INDEX IF NOT EXISTS `field_groups_created_at_idx` ON `field_groups` (`created_at`)" },
  { index: "field_groups_fields_options_order_idx", sql: "CREATE INDEX IF NOT EXISTS `field_groups_fields_options_order_idx` ON `field_groups_fields_options` (`_order`)" },
  { index: "field_groups_fields_options_parent_id_idx", sql: "CREATE INDEX IF NOT EXISTS `field_groups_fields_options_parent_id_idx` ON `field_groups_fields_options` (`_parent_id`)" },
  { index: "field_groups_fields_order_idx", sql: "CREATE INDEX IF NOT EXISTS `field_groups_fields_order_idx` ON `field_groups_fields` (`_order`)" },
  { index: "field_groups_fields_parent_id_idx", sql: "CREATE INDEX IF NOT EXISTS `field_groups_fields_parent_id_idx` ON `field_groups_fields` (`_parent_id`)" },
  { index: "field_groups_target_collections_order_idx", sql: "CREATE INDEX IF NOT EXISTS `field_groups_target_collections_order_idx` ON `field_groups_target_collections` (`order`)" },
  { index: "field_groups_target_collections_parent_idx", sql: "CREATE INDEX IF NOT EXISTS `field_groups_target_collections_parent_idx` ON `field_groups_target_collections` (`parent_id`)" },
  { index: "field_groups_updated_at_idx", sql: "CREATE INDEX IF NOT EXISTS `field_groups_updated_at_idx` ON `field_groups` (`updated_at`)" },
  { index: "page_templates_blocks_loop_order_idx", sql: "CREATE INDEX IF NOT EXISTS `page_templates_blocks_loop_order_idx` ON `page_templates_blocks_loop` (`_order`)" },
  { index: "page_templates_blocks_loop_parent_id_idx", sql: "CREATE INDEX IF NOT EXISTS `page_templates_blocks_loop_parent_id_idx` ON `page_templates_blocks_loop` (`_parent_id`)" },
  { index: "page_templates_blocks_loop_path_idx", sql: "CREATE INDEX IF NOT EXISTS `page_templates_blocks_loop_path_idx` ON `page_templates_blocks_loop` (`_path`)" },
  { index: "page_templates_blocks_loop_template_idx", sql: "CREATE INDEX IF NOT EXISTS `page_templates_blocks_loop_template_idx` ON `page_templates_blocks_loop` (`template_id`)" },
  { index: "page_templates_blocks_section_order_idx", sql: "CREATE INDEX IF NOT EXISTS `page_templates_blocks_section_order_idx` ON `page_templates_blocks_section` (`_order`)" },
  { index: "page_templates_blocks_section_parent_id_idx", sql: "CREATE INDEX IF NOT EXISTS `page_templates_blocks_section_parent_id_idx` ON `page_templates_blocks_section` (`_parent_id`)" },
  { index: "page_templates_blocks_section_path_idx", sql: "CREATE INDEX IF NOT EXISTS `page_templates_blocks_section_path_idx` ON `page_templates_blocks_section` (`_path`)" },
  { index: "pages_blocks_loop_order_idx", sql: "CREATE INDEX IF NOT EXISTS `pages_blocks_loop_order_idx` ON `pages_blocks_loop` (`_order`)" },
  { index: "pages_blocks_loop_parent_id_idx", sql: "CREATE INDEX IF NOT EXISTS `pages_blocks_loop_parent_id_idx` ON `pages_blocks_loop` (`_parent_id`)" },
  { index: "pages_blocks_loop_path_idx", sql: "CREATE INDEX IF NOT EXISTS `pages_blocks_loop_path_idx` ON `pages_blocks_loop` (`_path`)" },
  { index: "pages_blocks_loop_template_idx", sql: "CREATE INDEX IF NOT EXISTS `pages_blocks_loop_template_idx` ON `pages_blocks_loop` (`template_id`)" },
  { index: "pages_blocks_section_order_idx", sql: "CREATE INDEX IF NOT EXISTS `pages_blocks_section_order_idx` ON `pages_blocks_section` (`_order`)" },
  { index: "pages_blocks_section_parent_id_idx", sql: "CREATE INDEX IF NOT EXISTS `pages_blocks_section_parent_id_idx` ON `pages_blocks_section` (`_parent_id`)" },
  { index: "pages_blocks_section_path_idx", sql: "CREATE INDEX IF NOT EXISTS `pages_blocks_section_path_idx` ON `pages_blocks_section` (`_path`)" },
  { index: "payload_locked_documents_rels_field_groups_id_idx", sql: "CREATE INDEX IF NOT EXISTS `payload_locked_documents_rels_field_groups_id_idx` ON `payload_locked_documents_rels` (`field_groups_id`)" },
  { index: "posts_blocks_loop_order_idx", sql: "CREATE INDEX IF NOT EXISTS `posts_blocks_loop_order_idx` ON `posts_blocks_loop` (`_order`)" },
  { index: "posts_blocks_loop_parent_id_idx", sql: "CREATE INDEX IF NOT EXISTS `posts_blocks_loop_parent_id_idx` ON `posts_blocks_loop` (`_parent_id`)" },
  { index: "posts_blocks_loop_path_idx", sql: "CREATE INDEX IF NOT EXISTS `posts_blocks_loop_path_idx` ON `posts_blocks_loop` (`_path`)" },
  { index: "posts_blocks_loop_template_idx", sql: "CREATE INDEX IF NOT EXISTS `posts_blocks_loop_template_idx` ON `posts_blocks_loop` (`template_id`)" },
  { index: "posts_blocks_section_order_idx", sql: "CREATE INDEX IF NOT EXISTS `posts_blocks_section_order_idx` ON `posts_blocks_section` (`_order`)" },
  { index: "posts_blocks_section_parent_id_idx", sql: "CREATE INDEX IF NOT EXISTS `posts_blocks_section_parent_id_idx` ON `posts_blocks_section` (`_parent_id`)" },
  { index: "posts_blocks_section_path_idx", sql: "CREATE INDEX IF NOT EXISTS `posts_blocks_section_path_idx` ON `posts_blocks_section` (`_path`)" },
  { index: "products_blocks_loop_order_idx", sql: "CREATE INDEX IF NOT EXISTS `products_blocks_loop_order_idx` ON `products_blocks_loop` (`_order`)" },
  { index: "products_blocks_loop_parent_id_idx", sql: "CREATE INDEX IF NOT EXISTS `products_blocks_loop_parent_id_idx` ON `products_blocks_loop` (`_parent_id`)" },
  { index: "products_blocks_loop_path_idx", sql: "CREATE INDEX IF NOT EXISTS `products_blocks_loop_path_idx` ON `products_blocks_loop` (`_path`)" },
  { index: "products_blocks_loop_template_idx", sql: "CREATE INDEX IF NOT EXISTS `products_blocks_loop_template_idx` ON `products_blocks_loop` (`template_id`)" },
  { index: "products_blocks_section_order_idx", sql: "CREATE INDEX IF NOT EXISTS `products_blocks_section_order_idx` ON `products_blocks_section` (`_order`)" },
  { index: "products_blocks_section_parent_id_idx", sql: "CREATE INDEX IF NOT EXISTS `products_blocks_section_parent_id_idx` ON `products_blocks_section` (`_parent_id`)" },
  { index: "products_blocks_section_path_idx", sql: "CREATE INDEX IF NOT EXISTS `products_blocks_section_path_idx` ON `products_blocks_section` (`_path`)" },
  { index: "shop_settings_blocks_loop_order_idx", sql: "CREATE INDEX IF NOT EXISTS `shop_settings_blocks_loop_order_idx` ON `shop_settings_blocks_loop` (`_order`)" },
  { index: "shop_settings_blocks_loop_parent_id_idx", sql: "CREATE INDEX IF NOT EXISTS `shop_settings_blocks_loop_parent_id_idx` ON `shop_settings_blocks_loop` (`_parent_id`)" },
  { index: "shop_settings_blocks_loop_path_idx", sql: "CREATE INDEX IF NOT EXISTS `shop_settings_blocks_loop_path_idx` ON `shop_settings_blocks_loop` (`_path`)" },
  { index: "shop_settings_blocks_loop_template_idx", sql: "CREATE INDEX IF NOT EXISTS `shop_settings_blocks_loop_template_idx` ON `shop_settings_blocks_loop` (`template_id`)" },
  { index: "shop_settings_blocks_section_order_idx", sql: "CREATE INDEX IF NOT EXISTS `shop_settings_blocks_section_order_idx` ON `shop_settings_blocks_section` (`_order`)" },
  { index: "shop_settings_blocks_section_parent_id_idx", sql: "CREATE INDEX IF NOT EXISTS `shop_settings_blocks_section_parent_id_idx` ON `shop_settings_blocks_section` (`_parent_id`)" },
  { index: "shop_settings_blocks_section_path_idx", sql: "CREATE INDEX IF NOT EXISTS `shop_settings_blocks_section_path_idx` ON `shop_settings_blocks_section` (`_path`)" },
]
