/**
 * Schema additions for the settings globals and the feature-toggle framework.
 *
 * GENERATED, then committed - do not hand-edit. Produced by the same
 * diff-and-verify procedure documented in
 * src/migrations/20260822_234701_builder_sections_loops_custom_fields.ts:
 * build the schema the CMS config wants, diff it against the schema production has,
 * and keep only the additions. Purely additive - 15 tables, 10 columns,
 * 12 indexes, nothing dropped or rewritten.
 *
 * Note the `ac_` table prefix: every new global sets `dbName` explicitly, which
 * is the naming convention going forward. The older tables predate it and are
 * renamed separately, so both spellings coexist until that migration lands.
 */

import type { SchemaColumn, SchemaIndex, SchemaTable } from './builderSchema'

export const SETTINGS_TABLES: SchemaTable[] = [
  { table: "ac_backup_settings", sql: "CREATE TABLE IF NOT EXISTS `ac_backup_settings` ( `id` integer PRIMARY KEY NOT NULL, `schedule_enabled` integer DEFAULT false, `schedule_frequency` text DEFAULT 'weekly', `schedule_time_of_day` text DEFAULT '03:00', `schedule_retention_count` numeric DEFAULT 7, `contents_database` integer DEFAULT true, `contents_media` integer DEFAULT true, `contents_settings` integer DEFAULT true, `destination_provider` text DEFAULT 'r2', `destination_r2_account_id` text, `destination_r2_bucket` text, `destination_r2_access_key_id` text, `destination_r2_secret_access_key` text, `destination_r2_path` text, `destination_s3_bucket` text, `destination_s3_region` text, `destination_s3_access_key_id` text, `destination_s3_secret_access_key` text, `destination_s3_path` text, `destination_ftp_host` text, `destination_ftp_port` numeric DEFAULT 21, `destination_ftp_username` text, `destination_ftp_password` text, `destination_ftp_path` text, `destination_sftp_host` text, `destination_sftp_port` numeric DEFAULT 22, `destination_sftp_username` text, `destination_sftp_password` text, `destination_sftp_private_key` text, `destination_sftp_path` text, `updated_at` text, `created_at` text )" },
  { table: "ac_email_settings", sql: "CREATE TABLE IF NOT EXISTS `ac_email_settings` ( `id` integer PRIMARY KEY NOT NULL, `provider` text DEFAULT 'resend', `from_name` text, `from_email` text, `reply_to_email` text, `resend_api_key` text, `ses_api_access_key_id` text, `ses_api_secret_access_key` text, `ses_api_region` text, `mailgun_api_key` text, `mailgun_domain` text, `mailgun_region` text DEFAULT 'us', `postmark_server_token` text, `postmark_message_stream` text DEFAULT 'outbound', `sendgrid_api_key` text, `cloudflare_api_token` text, `cloudflare_account_id` text, `smtp_host` text, `smtp_port` numeric DEFAULT 587, `smtp_username` text, `smtp_password` text, `testing_test_recipient` text, `updated_at` text, `created_at` text )" },
  { table: "ac_form_settings", sql: "CREATE TABLE IF NOT EXISTS `ac_form_settings` ( `id` integer PRIMARY KEY NOT NULL, `submissions_store_submissions` integer DEFAULT true, `submissions_retention_days` numeric DEFAULT 365, `submissions_send_admin_notification` integer DEFAULT true, `submissions_notification_recipients` text, `spam_honeypot` integer DEFAULT true, `spam_minimum_fill_time_seconds` numeric DEFAULT 3, `spam_turnstile` integer DEFAULT false, `spam_turnstile_site_key` text, `spam_turnstile_secret_key` text, `defaults_submit_button_label` text DEFAULT 'Submit', `defaults_success_message` text DEFAULT 'Thank you - we have received your message and will be in touch shortly.', `defaults_error_message` text DEFAULT 'Sorry, something went wrong and your message was not sent. Please try again.', `updated_at` text, `created_at` text )" },
  { table: "ac_language_settings", sql: "CREATE TABLE IF NOT EXISTS `ac_language_settings` ( `id` integer PRIMARY KEY NOT NULL, `multilingual_enabled` integer DEFAULT false, `multilingual_default_locale` text DEFAULT 'en-AU', `multilingual_fallback_to_default` integer DEFAULT true, `multilingual_show_language_switcher` integer DEFAULT true, `multilingual_switcher_position` text DEFAULT 'header', `updated_at` text, `created_at` text )" },
  { table: "ac_language_settings_multilingual_active_locales", sql: "CREATE TABLE IF NOT EXISTS `ac_language_settings_multilingual_active_locales` ( `order` integer NOT NULL, `parent_id` integer NOT NULL, `value` text, `id` integer PRIMARY KEY NOT NULL, FOREIGN KEY (`parent_id`) REFERENCES `ac_language_settings`(`id`) ON UPDATE no action ON DELETE cascade )" },
  { table: "ac_media_settings", sql: "CREATE TABLE IF NOT EXISTS `ac_media_settings` ( `id` integer PRIMARY KEY NOT NULL, `optimisation_provider` text DEFAULT 'none', `optimisation_quality` numeric DEFAULT 82, `optimisation_convert_to_webp` integer DEFAULT true, `optimisation_convert_to_avif` integer DEFAULT false, `optimisation_strip_metadata` integer DEFAULT true, `resizing_max_width` numeric DEFAULT 2560, `resizing_max_height` numeric DEFAULT 2560, `resizing_generate_responsive_sizes` integer DEFAULT true, `delivery_cloudflare_account_hash` text, `delivery_delivery_url_prefix` text, `bulk_batch_size` numeric DEFAULT 25, `updated_at` text, `created_at` text )" },
  { table: "ac_media_settings_resizing_responsive_widths", sql: "CREATE TABLE IF NOT EXISTS `ac_media_settings_resizing_responsive_widths` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `id` text PRIMARY KEY NOT NULL, `width` numeric, FOREIGN KEY (`_parent_id`) REFERENCES `ac_media_settings`(`id`) ON UPDATE no action ON DELETE cascade )" },
  { table: "ac_member_settings", sql: "CREATE TABLE IF NOT EXISTS `ac_member_settings` ( `id` integer PRIMARY KEY NOT NULL, `registration_allow_signup` integer DEFAULT false, `registration_require_email_verification` integer DEFAULT true, `registration_default_tier` text, `access_redirect_after_login` text DEFAULT '/account', `access_members_only_redirect` text DEFAULT '/membership', `access_teaser_mode` text DEFAULT 'excerpt', `billing_currency` text DEFAULT 'AUD', `billing_allow_cancellation` integer DEFAULT true, `billing_proration` integer DEFAULT true, `emails_welcome_subject` text DEFAULT 'Welcome aboard', `emails_welcome_body` text, `emails_expiry_reminder_days` numeric DEFAULT 7, `updated_at` text, `created_at` text )" },
  { table: "ac_payment_settings", sql: "CREATE TABLE IF NOT EXISTS `ac_payment_settings` ( `id` integer PRIMARY KEY NOT NULL, `stripe_enabled` integer DEFAULT false, `stripe_test_mode` integer DEFAULT true, `stripe_publishable_key` text, `stripe_secret_key` text, `stripe_webhook_signing_secret` text, `paypal_enabled` integer DEFAULT false, `paypal_environment` text DEFAULT 'sandbox', `paypal_client_id` text, `paypal_client_secret` text, `paypal_allow_pay_pal_later` integer DEFAULT false, `general_currency` text DEFAULT 'AUD', `general_capture_method` text DEFAULT 'automatic', `general_statement_descriptor` text, `updated_at` text, `created_at` text )" },
  { table: "ac_security_settings", sql: "CREATE TABLE IF NOT EXISTS `ac_security_settings` ( `id` integer PRIMARY KEY NOT NULL, `login_protection_max_login_attempts` numeric DEFAULT 5, `login_protection_lockout_minutes` numeric DEFAULT 15, `login_protection_require_two_factor_for_admins` integer DEFAULT false, `login_protection_session_timeout_minutes` numeric DEFAULT 720, `headers_hsts` integer DEFAULT true, `headers_x_frame_options` text DEFAULT 'SAMEORIGIN', `headers_x_content_type_options` integer DEFAULT true, `headers_referrer_policy` text DEFAULT 'strict-origin-when-cross-origin', `headers_permissions_policy` text, `headers_content_security_policy` text, `rate_limiting_enabled` integer DEFAULT true, `rate_limiting_requests_per_minute` numeric DEFAULT 120, `rate_limiting_apply_to_api` integer DEFAULT true, `rate_limiting_apply_to_forms` integer DEFAULT true, `hardening_block_probe_paths` integer DEFAULT true, `hardening_disable_directory_listing` integer DEFAULT true, `hardening_hide_cms_fingerprint` integer DEFAULT false, `audit_log_enabled` integer DEFAULT true, `audit_log_retention_days` numeric DEFAULT 90, `updated_at` text, `created_at` text )" },
  { table: "ac_seo_settings", sql: "CREATE TABLE IF NOT EXISTS `ac_seo_settings` ( `id` integer PRIMARY KEY NOT NULL, `defaults_title_template` text DEFAULT '%page% | %site%', `defaults_meta_description` text, `defaults_default_og_image_id` integer, `defaults_twitter_handle` text, `indexing_allow_indexing` integer DEFAULT true, `indexing_noindex_paths` text, `indexing_custom_robots_txt` text, `verification_google` text, `verification_bing` text, `verification_pinterest` text, `analytics_ga4_measurement_id` text, `analytics_gtm_container_id` text, `analytics_meta_pixel_id` text, `analytics_require_cookie_consent` integer DEFAULT true, `schema_organisation_name` text, `schema_type` text DEFAULT 'business', `schema_logo_id` integer, `sitemap_enabled` integer DEFAULT true, `sitemap_change_frequency` text DEFAULT 'weekly', `sitemap_exclude_paths` text, `custom_code_head_scripts` text, `custom_code_body_end_scripts` text, `updated_at` text, `created_at` text, FOREIGN KEY (`defaults_default_og_image_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null, FOREIGN KEY (`schema_logo_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null )" },
  { table: "ac_seo_settings_schema_same_as", sql: "CREATE TABLE IF NOT EXISTS `ac_seo_settings_schema_same_as` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `id` text PRIMARY KEY NOT NULL, `url` text, FOREIGN KEY (`_parent_id`) REFERENCES `ac_seo_settings`(`id`) ON UPDATE no action ON DELETE cascade )" },
  { table: "ac_speed_settings", sql: "CREATE TABLE IF NOT EXISTS `ac_speed_settings` ( `id` integer PRIMARY KEY NOT NULL, `caching_page_cache` integer DEFAULT false, `caching_cache_ttl_seconds` numeric DEFAULT 3600, `caching_cache_logged_in_users` integer DEFAULT false, `caching_purge_on_publish` integer DEFAULT true, `assets_minify_css` integer DEFAULT false, `assets_minify_js` integer DEFAULT false, `assets_combine_css` integer DEFAULT false, `assets_defer_js` integer DEFAULT false, `assets_remove_unused_css` integer DEFAULT false, `assets_preload_critical_css` integer DEFAULT false, `media_lazy_load_images` integer DEFAULT true, `media_lazy_load_iframes` integer DEFAULT true, `media_add_image_dimensions` integer DEFAULT true, `media_disable_emoji_script` integer DEFAULT false, `fonts_preload_fonts` integer DEFAULT false, `fonts_font_display_swap` integer DEFAULT true, `advanced_delay_js_execution` integer DEFAULT false, `updated_at` text, `created_at` text )" },
  { table: "ac_speed_settings_advanced_preconnect_origins", sql: "CREATE TABLE IF NOT EXISTS `ac_speed_settings_advanced_preconnect_origins` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `id` text PRIMARY KEY NOT NULL, `url` text, FOREIGN KEY (`_parent_id`) REFERENCES `ac_speed_settings`(`id`) ON UPDATE no action ON DELETE cascade )" },
  { table: "ac_speed_settings_advanced_prefetch_dns", sql: "CREATE TABLE IF NOT EXISTS `ac_speed_settings_advanced_prefetch_dns` ( `_order` integer NOT NULL, `_parent_id` integer NOT NULL, `id` text PRIMARY KEY NOT NULL, `domain` text, FOREIGN KEY (`_parent_id`) REFERENCES `ac_speed_settings`(`id`) ON UPDATE no action ON DELETE cascade )" },
]

export const SETTINGS_COLUMNS: SchemaColumn[] = [
  { table: "site_settings", column: "features_ab_testing", sql: "ALTER TABLE `site_settings` ADD `features_ab_testing` INTEGER DEFAULT false" },
  { table: "site_settings", column: "features_backups", sql: "ALTER TABLE `site_settings` ADD `features_backups` INTEGER DEFAULT false" },
  { table: "site_settings", column: "features_email", sql: "ALTER TABLE `site_settings` ADD `features_email` INTEGER DEFAULT false" },
  { table: "site_settings", column: "features_forms", sql: "ALTER TABLE `site_settings` ADD `features_forms` INTEGER DEFAULT false" },
  { table: "site_settings", column: "features_media", sql: "ALTER TABLE `site_settings` ADD `features_media` INTEGER DEFAULT false" },
  { table: "site_settings", column: "features_members", sql: "ALTER TABLE `site_settings` ADD `features_members` INTEGER DEFAULT false" },
  { table: "site_settings", column: "features_multilingual", sql: "ALTER TABLE `site_settings` ADD `features_multilingual` INTEGER DEFAULT false" },
  { table: "site_settings", column: "features_security", sql: "ALTER TABLE `site_settings` ADD `features_security` INTEGER DEFAULT true" },
  { table: "site_settings", column: "features_seo", sql: "ALTER TABLE `site_settings` ADD `features_seo` INTEGER DEFAULT true" },
  { table: "site_settings", column: "features_speed", sql: "ALTER TABLE `site_settings` ADD `features_speed` INTEGER DEFAULT false" },
]

export const SETTINGS_INDEXES: SchemaIndex[] = [
  { index: "ac_language_settings_multilingual_active_locales_order_idx", sql: "CREATE INDEX IF NOT EXISTS `ac_language_settings_multilingual_active_locales_order_idx` ON `ac_language_settings_multilingual_active_locales` (`order`)" },
  { index: "ac_language_settings_multilingual_active_locales_parent_idx", sql: "CREATE INDEX IF NOT EXISTS `ac_language_settings_multilingual_active_locales_parent_idx` ON `ac_language_settings_multilingual_active_locales` (`parent_id`)" },
  { index: "ac_media_settings_resizing_responsive_widths_order_idx", sql: "CREATE INDEX IF NOT EXISTS `ac_media_settings_resizing_responsive_widths_order_idx` ON `ac_media_settings_resizing_responsive_widths` (`_order`)" },
  { index: "ac_media_settings_resizing_responsive_widths_parent_id_idx", sql: "CREATE INDEX IF NOT EXISTS `ac_media_settings_resizing_responsive_widths_parent_id_idx` ON `ac_media_settings_resizing_responsive_widths` (`_parent_id`)" },
  { index: "ac_seo_settings_defaults_defaults_default_og_image_idx", sql: "CREATE INDEX IF NOT EXISTS `ac_seo_settings_defaults_defaults_default_og_image_idx` ON `ac_seo_settings` (`defaults_default_og_image_id`)" },
  { index: "ac_seo_settings_schema_same_as_order_idx", sql: "CREATE INDEX IF NOT EXISTS `ac_seo_settings_schema_same_as_order_idx` ON `ac_seo_settings_schema_same_as` (`_order`)" },
  { index: "ac_seo_settings_schema_same_as_parent_id_idx", sql: "CREATE INDEX IF NOT EXISTS `ac_seo_settings_schema_same_as_parent_id_idx` ON `ac_seo_settings_schema_same_as` (`_parent_id`)" },
  { index: "ac_seo_settings_schema_schema_logo_idx", sql: "CREATE INDEX IF NOT EXISTS `ac_seo_settings_schema_schema_logo_idx` ON `ac_seo_settings` (`schema_logo_id`)" },
  { index: "ac_speed_settings_advanced_preconnect_origins_order_idx", sql: "CREATE INDEX IF NOT EXISTS `ac_speed_settings_advanced_preconnect_origins_order_idx` ON `ac_speed_settings_advanced_preconnect_origins` (`_order`)" },
  { index: "ac_speed_settings_advanced_preconnect_origins_parent_id_idx", sql: "CREATE INDEX IF NOT EXISTS `ac_speed_settings_advanced_preconnect_origins_parent_id_idx` ON `ac_speed_settings_advanced_preconnect_origins` (`_parent_id`)" },
  { index: "ac_speed_settings_advanced_prefetch_dns_order_idx", sql: "CREATE INDEX IF NOT EXISTS `ac_speed_settings_advanced_prefetch_dns_order_idx` ON `ac_speed_settings_advanced_prefetch_dns` (`_order`)" },
  { index: "ac_speed_settings_advanced_prefetch_dns_parent_id_idx", sql: "CREATE INDEX IF NOT EXISTS `ac_speed_settings_advanced_prefetch_dns_parent_id_idx` ON `ac_speed_settings_advanced_prefetch_dns` (`_parent_id`)" },
]
