/**
 * Old -> new table names for the `eg_` (Engage) prefix rename.
 *
 * GENERATED, then committed - do not hand-edit. Regenerate with:
 *
 *   NODE_OPTIONS=--no-deprecation PAYLOAD_SECRET=ignore \
 *     npx tsx scripts/generateTableRenames.mts
 *
 * That script reads the new parent table names from every collection's and
 * global's `dbName` in src/engage.config.ts, reads the real table list from the
 * local emulated D1 (which tracks the same migration state as production), and
 * rewrites each child and version table by its parent - so nothing here is
 * typed by hand. It must be run against a database that has not yet been
 * renamed. See the script's own header for the full procedure.
 *
 * Deliberately absent: payload_migrations, payload_preferences,
 * payload_preferences_rels, payload_locked_documents,
 * payload_locked_documents_rels and payload_kv (the engine's own bookkeeping -
 * renaming them breaks migration tracking and admin state), and Cloudflare's
 * own _cf_METADATA.
 */

export const TABLE_RENAMES: { from: string; to: string }[] = [
  { from: '_events_v', to: '_eg_events_v' },
  { from: '_pages_v', to: '_eg_pages_v' },
  { from: '_pages_v_blocks_cta_banner', to: '_eg_pages_v_blocks_cta_banner' },
  { from: '_pages_v_blocks_event_grid', to: '_eg_pages_v_blocks_event_grid' },
  { from: '_pages_v_blocks_faq', to: '_eg_pages_v_blocks_faq' },
  { from: '_pages_v_blocks_gallery', to: '_eg_pages_v_blocks_gallery' },
  { from: '_pages_v_blocks_hero', to: '_eg_pages_v_blocks_hero' },
  { from: '_pages_v_blocks_image_text', to: '_eg_pages_v_blocks_image_text' },
  { from: '_pages_v_blocks_loop', to: '_eg_pages_v_blocks_loop' },
  { from: '_pages_v_blocks_product_grid', to: '_eg_pages_v_blocks_product_grid' },
  { from: '_pages_v_blocks_rich_text', to: '_eg_pages_v_blocks_rich_text' },
  { from: '_pages_v_blocks_section', to: '_eg_pages_v_blocks_section' },
  { from: '_pages_v_rels', to: '_eg_pages_v_rels' },
  { from: '_posts_v', to: '_eg_posts_v' },
  { from: '_posts_v_blocks_cta_banner', to: '_eg_posts_v_blocks_cta_banner' },
  { from: '_posts_v_blocks_event_grid', to: '_eg_posts_v_blocks_event_grid' },
  { from: '_posts_v_blocks_faq', to: '_eg_posts_v_blocks_faq' },
  { from: '_posts_v_blocks_gallery', to: '_eg_posts_v_blocks_gallery' },
  { from: '_posts_v_blocks_hero', to: '_eg_posts_v_blocks_hero' },
  { from: '_posts_v_blocks_image_text', to: '_eg_posts_v_blocks_image_text' },
  { from: '_posts_v_blocks_loop', to: '_eg_posts_v_blocks_loop' },
  { from: '_posts_v_blocks_product_grid', to: '_eg_posts_v_blocks_product_grid' },
  { from: '_posts_v_blocks_rich_text', to: '_eg_posts_v_blocks_rich_text' },
  { from: '_posts_v_blocks_section', to: '_eg_posts_v_blocks_section' },
  { from: '_posts_v_rels', to: '_eg_posts_v_rels' },
  { from: '_posts_v_version_categories', to: '_eg_posts_v_version_categories' },
  { from: '_products_v', to: '_eg_products_v' },
  { from: '_products_v_blocks_cta_banner', to: '_eg_products_v_blocks_cta_banner' },
  { from: '_products_v_blocks_event_grid', to: '_eg_products_v_blocks_event_grid' },
  { from: '_products_v_blocks_faq', to: '_eg_products_v_blocks_faq' },
  { from: '_products_v_blocks_gallery', to: '_eg_products_v_blocks_gallery' },
  { from: '_products_v_blocks_hero', to: '_eg_products_v_blocks_hero' },
  { from: '_products_v_blocks_image_text', to: '_eg_products_v_blocks_image_text' },
  { from: '_products_v_blocks_loop', to: '_eg_products_v_blocks_loop' },
  { from: '_products_v_blocks_product_grid', to: '_eg_products_v_blocks_product_grid' },
  { from: '_products_v_blocks_rich_text', to: '_eg_products_v_blocks_rich_text' },
  { from: '_products_v_blocks_section', to: '_eg_products_v_blocks_section' },
  { from: '_products_v_rels', to: '_eg_products_v_rels' },
  { from: 'ac_backup_settings', to: 'eg_backup_settings' },
  { from: 'ac_email_settings', to: 'eg_email_settings' },
  { from: 'ac_form_settings', to: 'eg_form_settings' },
  { from: 'ac_language_settings', to: 'eg_language_settings' },
  { from: 'ac_language_settings_multilingual_active_locales', to: 'eg_language_settings_multilingual_active_locales' },
  { from: 'ac_media_settings', to: 'eg_media_settings' },
  { from: 'ac_media_settings_resizing_responsive_widths', to: 'eg_media_settings_resizing_responsive_widths' },
  { from: 'ac_member_settings', to: 'eg_member_settings' },
  { from: 'ac_payment_settings', to: 'eg_payment_settings' },
  { from: 'ac_security_settings', to: 'eg_security_settings' },
  { from: 'ac_seo_settings', to: 'eg_seo_settings' },
  { from: 'ac_seo_settings_schema_same_as', to: 'eg_seo_settings_schema_same_as' },
  { from: 'ac_speed_settings', to: 'eg_speed_settings' },
  { from: 'ac_speed_settings_advanced_preconnect_origins', to: 'eg_speed_settings_advanced_preconnect_origins' },
  { from: 'ac_speed_settings_advanced_prefetch_dns', to: 'eg_speed_settings_advanced_prefetch_dns' },
  { from: 'addresses', to: 'eg_addresses' },
  { from: 'blog_settings', to: 'eg_blog_settings' },
  { from: 'blog_settings_blocks_cta_banner', to: 'eg_blog_settings_blocks_cta_banner' },
  { from: 'blog_settings_blocks_event_grid', to: 'eg_blog_settings_blocks_event_grid' },
  { from: 'blog_settings_blocks_faq', to: 'eg_blog_settings_blocks_faq' },
  { from: 'blog_settings_blocks_gallery', to: 'eg_blog_settings_blocks_gallery' },
  { from: 'blog_settings_blocks_hero', to: 'eg_blog_settings_blocks_hero' },
  { from: 'blog_settings_blocks_image_text', to: 'eg_blog_settings_blocks_image_text' },
  { from: 'blog_settings_blocks_loop', to: 'eg_blog_settings_blocks_loop' },
  { from: 'blog_settings_blocks_product_grid', to: 'eg_blog_settings_blocks_product_grid' },
  { from: 'blog_settings_blocks_rich_text', to: 'eg_blog_settings_blocks_rich_text' },
  { from: 'blog_settings_blocks_section', to: 'eg_blog_settings_blocks_section' },
  { from: 'blog_settings_rels', to: 'eg_blog_settings_rels' },
  { from: 'carts', to: 'eg_carts' },
  { from: 'carts_items', to: 'eg_carts_items' },
  { from: 'event_rsvps', to: 'eg_event_rsvps' },
  { from: 'events', to: 'eg_events' },
  { from: 'faq_settings', to: 'eg_faq_settings' },
  { from: 'faq_settings_blocks_cta_banner', to: 'eg_faq_settings_blocks_cta_banner' },
  { from: 'faq_settings_blocks_event_grid', to: 'eg_faq_settings_blocks_event_grid' },
  { from: 'faq_settings_blocks_faq', to: 'eg_faq_settings_blocks_faq' },
  { from: 'faq_settings_blocks_gallery', to: 'eg_faq_settings_blocks_gallery' },
  { from: 'faq_settings_blocks_hero', to: 'eg_faq_settings_blocks_hero' },
  { from: 'faq_settings_blocks_image_text', to: 'eg_faq_settings_blocks_image_text' },
  { from: 'faq_settings_blocks_loop', to: 'eg_faq_settings_blocks_loop' },
  { from: 'faq_settings_blocks_product_grid', to: 'eg_faq_settings_blocks_product_grid' },
  { from: 'faq_settings_blocks_rich_text', to: 'eg_faq_settings_blocks_rich_text' },
  { from: 'faq_settings_blocks_section', to: 'eg_faq_settings_blocks_section' },
  { from: 'faq_settings_rels', to: 'eg_faq_settings_rels' },
  { from: 'faqs', to: 'eg_faqs' },
  { from: 'field_groups', to: 'eg_field_groups' },
  { from: 'field_groups_fields', to: 'eg_field_groups_fields' },
  { from: 'field_groups_fields_options', to: 'eg_field_groups_fields_options' },
  { from: 'field_groups_target_collections', to: 'eg_field_groups_target_collections' },
  { from: 'footer', to: 'eg_footer' },
  { from: 'footer_columns', to: 'eg_footer_columns' },
  { from: 'footer_columns_links', to: 'eg_footer_columns_links' },
  { from: 'footer_socials_links', to: 'eg_footer_socials_links' },
  { from: 'header', to: 'eg_header' },
  { from: 'header_menu', to: 'eg_header_menu' },
  { from: 'header_menu_children', to: 'eg_header_menu_children' },
  { from: 'header_socials_links', to: 'eg_header_socials_links' },
  { from: 'integrations', to: 'eg_integrations' },
  { from: 'media', to: 'eg_media' },
  { from: 'navigation', to: 'eg_navigation' },
  { from: 'navigation_items', to: 'eg_navigation_items' },
  { from: 'orders', to: 'eg_orders' },
  { from: 'orders_items', to: 'eg_orders_items' },
  { from: 'orders_rels', to: 'eg_orders_rels' },
  { from: 'page_templates', to: 'eg_page_templates' },
  { from: 'page_templates_blocks_cta_banner', to: 'eg_page_templates_blocks_cta_banner' },
  { from: 'page_templates_blocks_event_grid', to: 'eg_page_templates_blocks_event_grid' },
  { from: 'page_templates_blocks_faq', to: 'eg_page_templates_blocks_faq' },
  { from: 'page_templates_blocks_gallery', to: 'eg_page_templates_blocks_gallery' },
  { from: 'page_templates_blocks_hero', to: 'eg_page_templates_blocks_hero' },
  { from: 'page_templates_blocks_image_text', to: 'eg_page_templates_blocks_image_text' },
  { from: 'page_templates_blocks_loop', to: 'eg_page_templates_blocks_loop' },
  { from: 'page_templates_blocks_product_grid', to: 'eg_page_templates_blocks_product_grid' },
  { from: 'page_templates_blocks_rich_text', to: 'eg_page_templates_blocks_rich_text' },
  { from: 'page_templates_blocks_section', to: 'eg_page_templates_blocks_section' },
  { from: 'page_templates_rels', to: 'eg_page_templates_rels' },
  { from: 'pages', to: 'eg_pages' },
  { from: 'pages_blocks_cta_banner', to: 'eg_pages_blocks_cta_banner' },
  { from: 'pages_blocks_event_grid', to: 'eg_pages_blocks_event_grid' },
  { from: 'pages_blocks_faq', to: 'eg_pages_blocks_faq' },
  { from: 'pages_blocks_gallery', to: 'eg_pages_blocks_gallery' },
  { from: 'pages_blocks_hero', to: 'eg_pages_blocks_hero' },
  { from: 'pages_blocks_image_text', to: 'eg_pages_blocks_image_text' },
  { from: 'pages_blocks_loop', to: 'eg_pages_blocks_loop' },
  { from: 'pages_blocks_product_grid', to: 'eg_pages_blocks_product_grid' },
  { from: 'pages_blocks_rich_text', to: 'eg_pages_blocks_rich_text' },
  { from: 'pages_blocks_section', to: 'eg_pages_blocks_section' },
  { from: 'pages_rels', to: 'eg_pages_rels' },
  { from: 'posts', to: 'eg_posts' },
  { from: 'posts_blocks_cta_banner', to: 'eg_posts_blocks_cta_banner' },
  { from: 'posts_blocks_event_grid', to: 'eg_posts_blocks_event_grid' },
  { from: 'posts_blocks_faq', to: 'eg_posts_blocks_faq' },
  { from: 'posts_blocks_gallery', to: 'eg_posts_blocks_gallery' },
  { from: 'posts_blocks_hero', to: 'eg_posts_blocks_hero' },
  { from: 'posts_blocks_image_text', to: 'eg_posts_blocks_image_text' },
  { from: 'posts_blocks_loop', to: 'eg_posts_blocks_loop' },
  { from: 'posts_blocks_product_grid', to: 'eg_posts_blocks_product_grid' },
  { from: 'posts_blocks_rich_text', to: 'eg_posts_blocks_rich_text' },
  { from: 'posts_blocks_section', to: 'eg_posts_blocks_section' },
  { from: 'posts_categories', to: 'eg_posts_categories' },
  { from: 'posts_rels', to: 'eg_posts_rels' },
  { from: 'products', to: 'eg_products' },
  { from: 'products_blocks_cta_banner', to: 'eg_products_blocks_cta_banner' },
  { from: 'products_blocks_event_grid', to: 'eg_products_blocks_event_grid' },
  { from: 'products_blocks_faq', to: 'eg_products_blocks_faq' },
  { from: 'products_blocks_gallery', to: 'eg_products_blocks_gallery' },
  { from: 'products_blocks_hero', to: 'eg_products_blocks_hero' },
  { from: 'products_blocks_image_text', to: 'eg_products_blocks_image_text' },
  { from: 'products_blocks_loop', to: 'eg_products_blocks_loop' },
  { from: 'products_blocks_product_grid', to: 'eg_products_blocks_product_grid' },
  { from: 'products_blocks_rich_text', to: 'eg_products_blocks_rich_text' },
  { from: 'products_blocks_section', to: 'eg_products_blocks_section' },
  { from: 'products_rels', to: 'eg_products_rels' },
  { from: 'shop_settings', to: 'eg_shop_settings' },
  { from: 'shop_settings_blocks_cta_banner', to: 'eg_shop_settings_blocks_cta_banner' },
  { from: 'shop_settings_blocks_event_grid', to: 'eg_shop_settings_blocks_event_grid' },
  { from: 'shop_settings_blocks_faq', to: 'eg_shop_settings_blocks_faq' },
  { from: 'shop_settings_blocks_gallery', to: 'eg_shop_settings_blocks_gallery' },
  { from: 'shop_settings_blocks_hero', to: 'eg_shop_settings_blocks_hero' },
  { from: 'shop_settings_blocks_image_text', to: 'eg_shop_settings_blocks_image_text' },
  { from: 'shop_settings_blocks_loop', to: 'eg_shop_settings_blocks_loop' },
  { from: 'shop_settings_blocks_product_grid', to: 'eg_shop_settings_blocks_product_grid' },
  { from: 'shop_settings_blocks_rich_text', to: 'eg_shop_settings_blocks_rich_text' },
  { from: 'shop_settings_blocks_section', to: 'eg_shop_settings_blocks_section' },
  { from: 'shop_settings_rels', to: 'eg_shop_settings_rels' },
  { from: 'site_settings', to: 'eg_site_settings' },
  { from: 'site_settings_footer_social_links', to: 'eg_site_settings_footer_social_links' },
  { from: 'transactions', to: 'eg_transactions' },
  { from: 'transactions_items', to: 'eg_transactions_items' },
  { from: 'users', to: 'eg_users' },
  { from: 'users_roles', to: 'eg_users_roles' },
  { from: 'users_sessions', to: 'eg_users_sessions' },
]
