import type { GlobalConfig, CollectionConfig } from '@/engine'

import { AbTests } from '@/features/abTesting/collections/ABTests'
import { AuditLog } from '@/features/security/auditLogCollection'
import { BackupSettings } from '@/features/backups/collection'
import { BlogSettings } from '@/cms/config/globals/BlogSettings'
import { Courses } from '@/features/courses/collections/Courses'
import { Enrolments } from '@/features/courses/collections/Enrolments'
import { EventRSVPs } from '@/features/events/collections/EventRSVPs'
import { Events } from '@/cms/config/collections/Events'
import { FAQs } from '@/cms/config/collections/FAQs'
import { FieldGroups } from '@/cms/config/collections/FieldGroups'
import { FormSubmissions } from '@/features/forms/collections/FormSubmissions'
import { Forms } from '@/features/forms/collections/Forms'
import { LessonProgress } from '@/features/courses/collections/LessonProgress'
import { Lessons } from '@/features/courses/collections/Lessons'
import { Media } from '@/cms/config/collections/Media'
import { MembershipTiers } from '@/features/members/collections/MembershipTiers'
import { Memberships } from '@/features/members/collections/Memberships'
import { PageTemplates } from '@/cms/config/collections/PageTemplates'
import { Pages } from '@/cms/config/collections/Pages'
import { Posts } from '@/cms/config/collections/Posts'
import { Users } from '@/cms/config/collections/Users'
import { Translations } from '@/cms/config/collections/Translations'
import { Footer } from '@/cms/config/globals/Footer'
import { Header } from '@/cms/config/globals/Header'
import { SeoSettings } from '@/cms/config/globals/SeoSettings'
import { ShopSettings } from '@/cms/config/globals/ShopSettings'
import { SiteSettings } from '@/cms/config/globals/SiteSettings'
import { SpeedSettings } from '@/cms/config/globals/SpeedSettings'
import { SecuritySettings } from '@/cms/config/globals/SecuritySettings'
import { PaymentSettings } from '@/cms/config/globals/PaymentSettings'
import { EmailSettings } from '@/cms/config/globals/EmailSettings'
import { FaqSettings } from '@/cms/config/globals/FaqSettings'
import { BlogSettings as BlogSettingsGlobal } from '@/cms/config/globals/BlogSettings'
import { FormSettings } from '@/cms/config/globals/FormSettings'
import { MediaSettings } from '@/cms/config/globals/MediaSettings'
import { IntegrationSettings } from '@/cms/config/globals/IntegrationSettings'
import { MemberSettings } from '@/cms/config/globals/MemberSettings'
import { LanguageSettings } from '@/cms/config/globals/LanguageSettings'
import { BackupSettings as BackupSettingsGlobal } from '@/cms/config/globals/BackupSettings'

import { Addresses } from '@/features/ecommerce/collections/Addresses'
import { Carts } from '@/features/ecommerce/collections/Carts'
import { Orders } from '@/features/ecommerce/collections/Orders'
import { Products } from '@/features/ecommerce/collections/Products'
import { Transactions } from '@/features/ecommerce/collections/Transactions'

import {
  findAbTests,
  findAbTestByID,
  countAbTests,
  createAbTest,
  updateAbTest,
  deleteAbTest,
  findAuditLogs,
  findAuditLogByID,
  countAuditLogs,
  findBackups,
  findBackupByID,
  countBackups,
  createBackup,
  updateBackup,
  deleteBackup,
  findCourses,
  findCourseByID,
  countCourses,
  createCourse,
  updateCourse,
  deleteCourse,
  findCourseVersions,
  findLatestCourseVersion,
  createCourseVersion,
  findEnrolments,
  findEnrolmentByID,
  countEnrolments,
  createEnrolment,
  updateEnrolment,
  deleteEnrolment,
  findEventRSVPs,
  findEventRSVPByID,
  countEventRSVPs,
  createEventRSVP,
  updateEventRSVP,
  deleteEventRSVP,
  findEvents,
  findEventByID,
  countEvents,
  createEvent,
  updateEvent,
  deleteEvent,
  findEventVersions,
  findLatestEventVersion,
  createEventVersion,
  findFaqs,
  findFaqByID,
  countFaqs,
  createFaq,
  updateFaq,
  deleteFaq,
  findFieldGroups,
  findFieldGroupByID,
  countFieldGroups,
  createFieldGroup,
  updateFieldGroup,
  deleteFieldGroup,
  findFormSubmissions,
  findFormSubmissionByID,
  countFormSubmissions,
  createFormSubmission,
  updateFormSubmission,
  deleteFormSubmission,
  findForms,
  findFormByID,
  countForms,
  createForm,
  updateForm,
  deleteForm,
  findLessonProgress,
  findLessonProgressByID,
  countLessonProgress,
  createLessonProgress,
  updateLessonProgress,
  deleteLessonProgress,
  findLessons,
  findLessonByID,
  countLessons,
  createLesson,
  updateLesson,
  deleteLesson,
  findMedia,
  findMediaByID,
  countMedia,
  createMedia,
  updateMedia,
  deleteMedia,
  findMembershipTiers,
  findMembershipTierByID,
  countMembershipTiers,
  createMembershipTier,
  updateMembershipTier,
  deleteMembershipTier,
  findMemberships,
  findMembershipByID,
  countMemberships,
  createMembership,
  updateMembership,
  deleteMembership,
  findPageTemplates,
  findPageTemplateByID,
  countPageTemplates,
  createPageTemplate,
  updatePageTemplate,
  deletePageTemplate,
  findPages,
  findPageByID,
  countPages,
  createPage,
  updatePage,
  deletePage,
  findPageVersions,
  findLatestPageVersion,
  createPageVersion,
  findPosts,
  findPostByID,
  countPosts,
  createPost,
  updatePost,
  deletePost,
  findPostVersions,
  findLatestPostVersion,
  createPostVersion,
  findUsers,
  findUserByID,
  countUsers,
  createUser,
  updateUser,
  deleteUser,
  findTranslations,
  findTranslationByID,
  countTranslations,
  createTranslation,
  updateTranslation,
  deleteTranslation,
  findFooter,
  updateFooter,
  findHeader,
  updateHeader,
  findSeoSettings,
  updateSeoSettings,
  findShopSettings,
  updateShopSettings,
  findSiteSettings,
  updateSiteSettings,
  findSpeedSettings,
  updateSpeedSettings,
  findSecuritySettings,
  updateSecuritySettings,
  findPaymentSettings,
  updatePaymentSettings,
  findEmailSettings,
  updateEmailSettings,
  findFaqSettings,
  updateFaqSettings,
  findFormSettings,
  updateFormSettings,
  findMediaSettings,
  updateMediaSettings,
  findIntegrationSettings,
  updateIntegrationSettings,
  findMemberSettings,
  updateMemberSettings,
  findLanguageSettings,
  updateLanguageSettings,
  findBackupSettings,
  updateBackupSettings,
  findAddresses,
  findAddressByID,
  countAddresses,
  createAddress,
  updateAddress,
  deleteAddress,
  findCarts,
  findCartByID,
  countCarts,
  createCart,
  updateCart,
  deleteCart,
  findOrders,
  findOrderByID,
  countOrders,
  createOrder,
  updateOrder,
  deleteOrder,
  findProducts,
  findProductByID,
  countProducts,
  createProduct,
  updateProduct,
  deleteProduct,
  findTransactions,
  findTransactionByID,
  countTransactions,
  createTransaction,
  updateTransaction,
  deleteTransaction,
} from '@/cms/db'

export const collections: (CollectionConfig | string)[] = [
  AbTests,
  AuditLog,
  BackupSettings,
  Courses,
  Enrolments,
  EventRSVPs,
  Events,
  FAQs,
  FieldGroups,
  FormSubmissions,
  Forms,
  LessonProgress,
  Lessons,
  Media,
  MembershipTiers,
  Memberships,
  PageTemplates,
  Pages,
  Posts,
  Users,
  Translations,
  Addresses,
  Carts,
  Orders,
  Products,
  Transactions,
]

export const globals: (GlobalConfig | string)[] = [
  BlogSettings,
  Footer,
  Header,
  SeoSettings,
  ShopSettings,
  SiteSettings,
  SpeedSettings,
  SecuritySettings,
  PaymentSettings,
  EmailSettings,
  FaqSettings,
  FormSettings,
  MediaSettings,
  IntegrationSettings,
  MemberSettings,
  LanguageSettings,
  BackupSettingsGlobal,
]

export const ops = {
  // AB Tests
  findAbTests,
  findAbTestByID,
  countAbTests,
  createAbTest,
  updateAbTest,
  deleteAbTest,
  // Audit Log
  findAuditLogs,
  findAuditLogByID,
  countAuditLogs,
  // Backups
  findBackups,
  findBackupByID,
  countBackups,
  createBackup,
  updateBackup,
  deleteBackup,
  // Courses
  findCourses,
  findCourseByID,
  countCourses,
  createCourse,
  updateCourse,
  deleteCourse,
  findCourseVersions,
  findLatestCourseVersion,
  createCourseVersion,
  // Enrolments
  findEnrolments,
  findEnrolmentByID,
  countEnrolments,
  createEnrolment,
  updateEnrolment,
  deleteEnrolment,
  // Event RSVPs
  findEventRSVPs,
  findEventRSVPByID,
  countEventRSVPs,
  createEventRSVP,
  updateEventRSVP,
  deleteEventRSVP,
  // Events
  findEvents,
  findEventByID,
  countEvents,
  createEvent,
  updateEvent,
  deleteEvent,
  findEventVersions,
  findLatestEventVersion,
  createEventVersion,
  // FAQs
  findFaqs,
  findFaqByID,
  countFaqs,
  createFaq,
  updateFaq,
  deleteFaq,
  // Field Groups
  findFieldGroups,
  findFieldGroupByID,
  countFieldGroups,
  createFieldGroup,
  updateFieldGroup,
  deleteFieldGroup,
  // Form Submissions
  findFormSubmissions,
  findFormSubmissionByID,
  countFormSubmissions,
  createFormSubmission,
  updateFormSubmission,
  deleteFormSubmission,
  // Forms
  findForms,
  findFormByID,
  countForms,
  createForm,
  updateForm,
  deleteForm,
  // Lesson Progress
  findLessonProgress,
  findLessonProgressByID,
  countLessonProgress,
  createLessonProgress,
  updateLessonProgress,
  deleteLessonProgress,
  // Lessons
  findLessons,
  findLessonByID,
  countLessons,
  createLesson,
  updateLesson,
  deleteLesson,
  // Media
  findMedia,
  findMediaByID,
  countMedia,
  createMedia,
  updateMedia,
  deleteMedia,
  // Membership Tiers
  findMembershipTiers,
  findMembershipTierByID,
  countMembershipTiers,
  createMembershipTier,
  updateMembershipTier,
  deleteMembershipTier,
  // Memberships
  findMemberships,
  findMembershipByID,
  countMemberships,
  createMembership,
  updateMembership,
  deleteMembership,
  // Page Templates
  findPageTemplates,
  findPageTemplateByID,
  countPageTemplates,
  createPageTemplate,
  updatePageTemplate,
  deletePageTemplate,
  // Pages
  findPages,
  findPageByID,
  countPages,
  createPage,
  updatePage,
  deletePage,
  findPageVersions,
  findLatestPageVersion,
  createPageVersion,
  // Posts
  findPosts,
  findPostByID,
  countPosts,
  createPost,
  updatePost,
  deletePost,
  findPostVersions,
  findLatestPostVersion,
  createPostVersion,
  // Users
  findUsers,
  findUserByID,
  countUsers,
  createUser,
  updateUser,
  deleteUser,
  // Translations
  findTranslations,
  findTranslationByID,
  countTranslations,
  createTranslation,
  updateTranslation,
  deleteTranslation,
  // Addresses
  findAddresses,
  findAddressByID,
  countAddresses,
  createAddress,
  updateAddress,
  deleteAddress,
  // Carts
  findCarts,
  findCartByID,
  countCarts,
  createCart,
  updateCart,
  deleteCart,
  // Orders
  findOrders,
  findOrderByID,
  countOrders,
  createOrder,
  updateOrder,
  deleteOrder,
  // Products
  findProducts,
  findProductByID,
  countProducts,
  createProduct,
  updateProduct,
  deleteProduct,
  // Transactions
  findTransactions,
  findTransactionByID,
  countTransactions,
  createTransaction,
  updateTransaction,
  deleteTransaction,
}
