import { MigrateUpArgs, MigrateDownArgs, sql } from '@/engine/db'

// Creates the Courses feature's tables: `eg_courses` and its version table,
// `eg_lessons` with the twelve child tables its page-builder sections need,
// `eg_enrolments` and `eg_lesson_progress`.
//
// Written to be safe to replay, for the same reason the backups and forms
// migrations are: the CLI cannot reach production D1 from this CI environment
// (see the note on the D1 binding in wrangler.jsonc), so every statement has to
// survive running against a database that already has it. Tables and indexes
// use IF NOT EXISTS; the four columns added to `eg_locked_documents_rels` are
// checked against PRAGMA table_info first, because SQLite has no
// ADD COLUMN IF NOT EXISTS.
//
// The SQL itself is not hand-written. It was generated by the engine's own
// migration tool from a scratch copy of the config with these four collections
// registered, then filtered down to the tables they own - a lesson carries the
// full block library, and transcribing sixteen tables by hand is how a schema
// ends up subtly different from the one the engine expects to read.

const TABLES = [
  `CREATE TABLE IF NOT EXISTS \`eg_courses\` (
	\`id\` integer PRIMARY KEY NOT NULL,
	\`title\` text,
	\`slug\` text,
	\`description\` text,
	\`cover_image_id\` integer,
	\`access_type\` text DEFAULT 'free',
	\`product_id\` integer,
	\`tier_slug\` text,
	\`seo_meta_title\` text,
	\`seo_meta_description\` text,
	\`seo_og_image_id\` integer,
	\`seo_no_index\` integer DEFAULT false,
	\`updated_at\` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	\`created_at\` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	\`_status\` text DEFAULT 'draft',
	FOREIGN KEY (\`cover_image_id\`) REFERENCES \`eg_media\`(\`id\`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (\`product_id\`) REFERENCES \`eg_products\`(\`id\`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (\`seo_og_image_id\`) REFERENCES \`eg_media\`(\`id\`) ON UPDATE no action ON DELETE set null
)`,
  `CREATE TABLE IF NOT EXISTS \`_eg_courses_v\` (
	\`id\` integer PRIMARY KEY NOT NULL,
	\`parent_id\` integer,
	\`version_title\` text,
	\`version_slug\` text,
	\`version_description\` text,
	\`version_cover_image_id\` integer,
	\`version_access_type\` text DEFAULT 'free',
	\`version_product_id\` integer,
	\`version_tier_slug\` text,
	\`version_seo_meta_title\` text,
	\`version_seo_meta_description\` text,
	\`version_seo_og_image_id\` integer,
	\`version_seo_no_index\` integer DEFAULT false,
	\`version_updated_at\` text,
	\`version_created_at\` text,
	\`version__status\` text DEFAULT 'draft',
	\`created_at\` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	\`updated_at\` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	\`latest\` integer,
	FOREIGN KEY (\`parent_id\`) REFERENCES \`eg_courses\`(\`id\`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (\`version_cover_image_id\`) REFERENCES \`eg_media\`(\`id\`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (\`version_product_id\`) REFERENCES \`eg_products\`(\`id\`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (\`version_seo_og_image_id\`) REFERENCES \`eg_media\`(\`id\`) ON UPDATE no action ON DELETE set null
)`,
  `CREATE TABLE IF NOT EXISTS \`eg_lessons_blocks_section\` (
	\`_order\` integer NOT NULL,
	\`_parent_id\` integer NOT NULL,
	\`_path\` text NOT NULL,
	\`id\` text PRIMARY KEY NOT NULL,
	\`columns\` text,
	\`design\` text,
	\`block_name\` text,
	FOREIGN KEY (\`_parent_id\`) REFERENCES \`eg_lessons\`(\`id\`) ON UPDATE no action ON DELETE cascade
)`,
  `CREATE TABLE IF NOT EXISTS \`eg_lessons_blocks_hero\` (
	\`_order\` integer NOT NULL,
	\`_parent_id\` integer NOT NULL,
	\`_path\` text NOT NULL,
	\`id\` text PRIMARY KEY NOT NULL,
	\`heading\` text NOT NULL,
	\`subheading\` text,
	\`background_image_id\` integer,
	\`primary_cta_label\` text,
	\`primary_cta_url\` text,
	\`secondary_cta_label\` text,
	\`secondary_cta_url\` text,
	\`design\` text,
	\`block_name\` text,
	FOREIGN KEY (\`background_image_id\`) REFERENCES \`eg_media\`(\`id\`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (\`_parent_id\`) REFERENCES \`eg_lessons\`(\`id\`) ON UPDATE no action ON DELETE cascade
)`,
  `CREATE TABLE IF NOT EXISTS \`eg_lessons_blocks_rich_text\` (
	\`_order\` integer NOT NULL,
	\`_parent_id\` integer NOT NULL,
	\`_path\` text NOT NULL,
	\`id\` text PRIMARY KEY NOT NULL,
	\`content\` text NOT NULL,
	\`design\` text,
	\`block_name\` text,
	FOREIGN KEY (\`_parent_id\`) REFERENCES \`eg_lessons\`(\`id\`) ON UPDATE no action ON DELETE cascade
)`,
  `CREATE TABLE IF NOT EXISTS \`eg_lessons_blocks_image_text\` (
	\`_order\` integer NOT NULL,
	\`_parent_id\` integer NOT NULL,
	\`_path\` text NOT NULL,
	\`id\` text PRIMARY KEY NOT NULL,
	\`image_id\` integer NOT NULL,
	\`content\` text NOT NULL,
	\`image_side\` text DEFAULT 'left',
	\`design\` text,
	\`block_name\` text,
	FOREIGN KEY (\`image_id\`) REFERENCES \`eg_media\`(\`id\`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (\`_parent_id\`) REFERENCES \`eg_lessons\`(\`id\`) ON UPDATE no action ON DELETE cascade
)`,
  `CREATE TABLE IF NOT EXISTS \`eg_lessons_blocks_product_grid\` (
	\`_order\` integer NOT NULL,
	\`_parent_id\` integer NOT NULL,
	\`_path\` text NOT NULL,
	\`id\` text PRIMARY KEY NOT NULL,
	\`heading\` text,
	\`category\` text,
	\`limit\` numeric DEFAULT 4,
	\`design\` text,
	\`block_name\` text,
	FOREIGN KEY (\`_parent_id\`) REFERENCES \`eg_lessons\`(\`id\`) ON UPDATE no action ON DELETE cascade
)`,
  `CREATE TABLE IF NOT EXISTS \`eg_lessons_blocks_event_grid\` (
	\`_order\` integer NOT NULL,
	\`_parent_id\` integer NOT NULL,
	\`_path\` text NOT NULL,
	\`id\` text PRIMARY KEY NOT NULL,
	\`heading\` text,
	\`show_past\` integer DEFAULT false,
	\`limit\` numeric DEFAULT 3,
	\`design\` text,
	\`block_name\` text,
	FOREIGN KEY (\`_parent_id\`) REFERENCES \`eg_lessons\`(\`id\`) ON UPDATE no action ON DELETE cascade
)`,
  `CREATE TABLE IF NOT EXISTS \`eg_lessons_blocks_gallery\` (
	\`_order\` integer NOT NULL,
	\`_parent_id\` integer NOT NULL,
	\`_path\` text NOT NULL,
	\`id\` text PRIMARY KEY NOT NULL,
	\`heading\` text,
	\`design\` text,
	\`block_name\` text,
	FOREIGN KEY (\`_parent_id\`) REFERENCES \`eg_lessons\`(\`id\`) ON UPDATE no action ON DELETE cascade
)`,
  `CREATE TABLE IF NOT EXISTS \`eg_lessons_blocks_faq\` (
	\`_order\` integer NOT NULL,
	\`_parent_id\` integer NOT NULL,
	\`_path\` text NOT NULL,
	\`id\` text PRIMARY KEY NOT NULL,
	\`heading\` text DEFAULT 'Frequently asked questions',
	\`source\` text DEFAULT 'category',
	\`category\` text,
	\`design\` text,
	\`block_name\` text,
	FOREIGN KEY (\`_parent_id\`) REFERENCES \`eg_lessons\`(\`id\`) ON UPDATE no action ON DELETE cascade
)`,
  `CREATE TABLE IF NOT EXISTS \`eg_lessons_blocks_cta_banner\` (
	\`_order\` integer NOT NULL,
	\`_parent_id\` integer NOT NULL,
	\`_path\` text NOT NULL,
	\`id\` text PRIMARY KEY NOT NULL,
	\`heading\` text NOT NULL,
	\`text\` text,
	\`button_label\` text,
	\`button_url\` text,
	\`style\` text DEFAULT 'dark',
	\`design\` text,
	\`block_name\` text,
	FOREIGN KEY (\`_parent_id\`) REFERENCES \`eg_lessons\`(\`id\`) ON UPDATE no action ON DELETE cascade
)`,
  `CREATE TABLE IF NOT EXISTS \`eg_lessons_blocks_loop\` (
	\`_order\` integer NOT NULL,
	\`_parent_id\` integer NOT NULL,
	\`_path\` text NOT NULL,
	\`id\` text PRIMARY KEY NOT NULL,
	\`heading\` text,
	\`template_id\` integer NOT NULL,
	\`source\` text DEFAULT 'products',
	\`category\` text,
	\`limit\` numeric DEFAULT 6,
	\`columns\` numeric DEFAULT 3,
	\`sort_by\` text DEFAULT 'newest',
	\`design\` text,
	\`block_name\` text,
	FOREIGN KEY (\`template_id\`) REFERENCES \`eg_page_templates\`(\`id\`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (\`_parent_id\`) REFERENCES \`eg_lessons\`(\`id\`) ON UPDATE no action ON DELETE cascade
)`,
  `CREATE TABLE IF NOT EXISTS \`eg_lessons_blocks_form\` (
	\`_order\` integer NOT NULL,
	\`_parent_id\` integer NOT NULL,
	\`_path\` text NOT NULL,
	\`id\` text PRIMARY KEY NOT NULL,
	\`form_id\` integer NOT NULL,
	\`heading\` text,
	\`show_title\` integer DEFAULT true,
	\`intro\` text,
	\`design\` text,
	\`block_name\` text,
	FOREIGN KEY (\`form_id\`) REFERENCES \`eg_forms\`(\`id\`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (\`_parent_id\`) REFERENCES \`eg_lessons\`(\`id\`) ON UPDATE no action ON DELETE cascade
)`,
  `CREATE TABLE IF NOT EXISTS \`eg_lessons_resources\` (
	\`_order\` integer NOT NULL,
	\`_parent_id\` integer NOT NULL,
	\`id\` text PRIMARY KEY NOT NULL,
	\`label\` text NOT NULL,
	\`file_id\` integer NOT NULL,
	FOREIGN KEY (\`file_id\`) REFERENCES \`eg_media\`(\`id\`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (\`_parent_id\`) REFERENCES \`eg_lessons\`(\`id\`) ON UPDATE no action ON DELETE cascade
)`,
  `CREATE TABLE IF NOT EXISTS \`eg_lessons\` (
	\`id\` integer PRIMARY KEY NOT NULL,
	\`title\` text NOT NULL,
	\`course_id\` integer NOT NULL,
	\`order\` numeric DEFAULT 0 NOT NULL,
	\`slug\` text,
	\`is_preview\` integer DEFAULT false,
	\`video_url\` text,
	\`duration_minutes\` numeric,
	\`updated_at\` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	\`created_at\` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	FOREIGN KEY (\`course_id\`) REFERENCES \`eg_courses\`(\`id\`) ON UPDATE no action ON DELETE set null
)`,
  `CREATE TABLE IF NOT EXISTS \`eg_lessons_rels\` (
	\`id\` integer PRIMARY KEY NOT NULL,
	\`order\` integer,
	\`parent_id\` integer NOT NULL,
	\`path\` text NOT NULL,
	\`eg_media_id\` integer,
	\`eg_faqs_id\` integer,
	FOREIGN KEY (\`parent_id\`) REFERENCES \`eg_lessons\`(\`id\`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (\`eg_media_id\`) REFERENCES \`eg_media\`(\`id\`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (\`eg_faqs_id\`) REFERENCES \`eg_faqs\`(\`id\`) ON UPDATE no action ON DELETE cascade
)`,
  `CREATE TABLE IF NOT EXISTS \`eg_enrolments\` (
	\`id\` integer PRIMARY KEY NOT NULL,
	\`user_id\` integer NOT NULL,
	\`course_id\` integer NOT NULL,
	\`enrolled_at\` text,
	\`status\` text DEFAULT 'active' NOT NULL,
	\`source\` text DEFAULT 'manual',
	\`updated_at\` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	\`created_at\` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	FOREIGN KEY (\`user_id\`) REFERENCES \`eg_users\`(\`id\`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (\`course_id\`) REFERENCES \`eg_courses\`(\`id\`) ON UPDATE no action ON DELETE set null
)`,
  `CREATE TABLE IF NOT EXISTS \`eg_lesson_progress\` (
	\`id\` integer PRIMARY KEY NOT NULL,
	\`user_id\` integer NOT NULL,
	\`lesson_id\` integer NOT NULL,
	\`course_id\` integer NOT NULL,
	\`completed\` integer DEFAULT true,
	\`completed_at\` text,
	\`updated_at\` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	\`created_at\` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	FOREIGN KEY (\`user_id\`) REFERENCES \`eg_users\`(\`id\`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (\`lesson_id\`) REFERENCES \`eg_lessons\`(\`id\`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (\`course_id\`) REFERENCES \`eg_courses\`(\`id\`) ON UPDATE no action ON DELETE set null
)`,
]

const INDEXES = [
  `CREATE UNIQUE INDEX IF NOT EXISTS \`eg_courses_slug_idx\` ON \`eg_courses\` (\`slug\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_courses_cover_image_idx\` ON \`eg_courses\` (\`cover_image_id\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_courses_access_type_idx\` ON \`eg_courses\` (\`access_type\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_courses_product_idx\` ON \`eg_courses\` (\`product_id\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_courses_seo_seo_og_image_idx\` ON \`eg_courses\` (\`seo_og_image_id\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_courses_updated_at_idx\` ON \`eg_courses\` (\`updated_at\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_courses_created_at_idx\` ON \`eg_courses\` (\`created_at\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_courses__status_idx\` ON \`eg_courses\` (\`_status\`)`,
  `CREATE INDEX IF NOT EXISTS \`_eg_courses_v_parent_idx\` ON \`_eg_courses_v\` (\`parent_id\`)`,
  `CREATE INDEX IF NOT EXISTS \`_eg_courses_v_version_version_slug_idx\` ON \`_eg_courses_v\` (\`version_slug\`)`,
  `CREATE INDEX IF NOT EXISTS \`_eg_courses_v_version_version_cover_image_idx\` ON \`_eg_courses_v\` (\`version_cover_image_id\`)`,
  `CREATE INDEX IF NOT EXISTS \`_eg_courses_v_version_version_access_type_idx\` ON \`_eg_courses_v\` (\`version_access_type\`)`,
  `CREATE INDEX IF NOT EXISTS \`_eg_courses_v_version_version_product_idx\` ON \`_eg_courses_v\` (\`version_product_id\`)`,
  `CREATE INDEX IF NOT EXISTS \`_eg_courses_v_version_seo_version_seo_og_image_idx\` ON \`_eg_courses_v\` (\`version_seo_og_image_id\`)`,
  `CREATE INDEX IF NOT EXISTS \`_eg_courses_v_version_version_updated_at_idx\` ON \`_eg_courses_v\` (\`version_updated_at\`)`,
  `CREATE INDEX IF NOT EXISTS \`_eg_courses_v_version_version_created_at_idx\` ON \`_eg_courses_v\` (\`version_created_at\`)`,
  `CREATE INDEX IF NOT EXISTS \`_eg_courses_v_version_version__status_idx\` ON \`_eg_courses_v\` (\`version__status\`)`,
  `CREATE INDEX IF NOT EXISTS \`_eg_courses_v_created_at_idx\` ON \`_eg_courses_v\` (\`created_at\`)`,
  `CREATE INDEX IF NOT EXISTS \`_eg_courses_v_updated_at_idx\` ON \`_eg_courses_v\` (\`updated_at\`)`,
  `CREATE INDEX IF NOT EXISTS \`_eg_courses_v_latest_idx\` ON \`_eg_courses_v\` (\`latest\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_blocks_section_order_idx\` ON \`eg_lessons_blocks_section\` (\`_order\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_blocks_section_parent_id_idx\` ON \`eg_lessons_blocks_section\` (\`_parent_id\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_blocks_section_path_idx\` ON \`eg_lessons_blocks_section\` (\`_path\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_blocks_hero_order_idx\` ON \`eg_lessons_blocks_hero\` (\`_order\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_blocks_hero_parent_id_idx\` ON \`eg_lessons_blocks_hero\` (\`_parent_id\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_blocks_hero_path_idx\` ON \`eg_lessons_blocks_hero\` (\`_path\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_blocks_hero_background_image_idx\` ON \`eg_lessons_blocks_hero\` (\`background_image_id\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_blocks_rich_text_order_idx\` ON \`eg_lessons_blocks_rich_text\` (\`_order\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_blocks_rich_text_parent_id_idx\` ON \`eg_lessons_blocks_rich_text\` (\`_parent_id\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_blocks_rich_text_path_idx\` ON \`eg_lessons_blocks_rich_text\` (\`_path\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_blocks_image_text_order_idx\` ON \`eg_lessons_blocks_image_text\` (\`_order\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_blocks_image_text_parent_id_idx\` ON \`eg_lessons_blocks_image_text\` (\`_parent_id\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_blocks_image_text_path_idx\` ON \`eg_lessons_blocks_image_text\` (\`_path\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_blocks_image_text_image_idx\` ON \`eg_lessons_blocks_image_text\` (\`image_id\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_blocks_product_grid_order_idx\` ON \`eg_lessons_blocks_product_grid\` (\`_order\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_blocks_product_grid_parent_id_idx\` ON \`eg_lessons_blocks_product_grid\` (\`_parent_id\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_blocks_product_grid_path_idx\` ON \`eg_lessons_blocks_product_grid\` (\`_path\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_blocks_event_grid_order_idx\` ON \`eg_lessons_blocks_event_grid\` (\`_order\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_blocks_event_grid_parent_id_idx\` ON \`eg_lessons_blocks_event_grid\` (\`_parent_id\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_blocks_event_grid_path_idx\` ON \`eg_lessons_blocks_event_grid\` (\`_path\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_blocks_gallery_order_idx\` ON \`eg_lessons_blocks_gallery\` (\`_order\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_blocks_gallery_parent_id_idx\` ON \`eg_lessons_blocks_gallery\` (\`_parent_id\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_blocks_gallery_path_idx\` ON \`eg_lessons_blocks_gallery\` (\`_path\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_blocks_faq_order_idx\` ON \`eg_lessons_blocks_faq\` (\`_order\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_blocks_faq_parent_id_idx\` ON \`eg_lessons_blocks_faq\` (\`_parent_id\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_blocks_faq_path_idx\` ON \`eg_lessons_blocks_faq\` (\`_path\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_blocks_cta_banner_order_idx\` ON \`eg_lessons_blocks_cta_banner\` (\`_order\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_blocks_cta_banner_parent_id_idx\` ON \`eg_lessons_blocks_cta_banner\` (\`_parent_id\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_blocks_cta_banner_path_idx\` ON \`eg_lessons_blocks_cta_banner\` (\`_path\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_blocks_loop_order_idx\` ON \`eg_lessons_blocks_loop\` (\`_order\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_blocks_loop_parent_id_idx\` ON \`eg_lessons_blocks_loop\` (\`_parent_id\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_blocks_loop_path_idx\` ON \`eg_lessons_blocks_loop\` (\`_path\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_blocks_loop_template_idx\` ON \`eg_lessons_blocks_loop\` (\`template_id\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_blocks_form_order_idx\` ON \`eg_lessons_blocks_form\` (\`_order\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_blocks_form_parent_id_idx\` ON \`eg_lessons_blocks_form\` (\`_parent_id\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_blocks_form_path_idx\` ON \`eg_lessons_blocks_form\` (\`_path\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_blocks_form_form_idx\` ON \`eg_lessons_blocks_form\` (\`form_id\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_resources_order_idx\` ON \`eg_lessons_resources\` (\`_order\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_resources_parent_id_idx\` ON \`eg_lessons_resources\` (\`_parent_id\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_resources_file_idx\` ON \`eg_lessons_resources\` (\`file_id\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_course_idx\` ON \`eg_lessons\` (\`course_id\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_order_idx\` ON \`eg_lessons\` (\`order\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_slug_idx\` ON \`eg_lessons\` (\`slug\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_is_preview_idx\` ON \`eg_lessons\` (\`is_preview\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_updated_at_idx\` ON \`eg_lessons\` (\`updated_at\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_created_at_idx\` ON \`eg_lessons\` (\`created_at\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_rels_order_idx\` ON \`eg_lessons_rels\` (\`order\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_rels_parent_idx\` ON \`eg_lessons_rels\` (\`parent_id\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_rels_path_idx\` ON \`eg_lessons_rels\` (\`path\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_rels_eg_media_id_idx\` ON \`eg_lessons_rels\` (\`eg_media_id\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lessons_rels_eg_faqs_id_idx\` ON \`eg_lessons_rels\` (\`eg_faqs_id\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_enrolments_user_idx\` ON \`eg_enrolments\` (\`user_id\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_enrolments_course_idx\` ON \`eg_enrolments\` (\`course_id\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_enrolments_enrolled_at_idx\` ON \`eg_enrolments\` (\`enrolled_at\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_enrolments_status_idx\` ON \`eg_enrolments\` (\`status\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_enrolments_updated_at_idx\` ON \`eg_enrolments\` (\`updated_at\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_enrolments_created_at_idx\` ON \`eg_enrolments\` (\`created_at\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lesson_progress_user_idx\` ON \`eg_lesson_progress\` (\`user_id\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lesson_progress_lesson_idx\` ON \`eg_lesson_progress\` (\`lesson_id\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lesson_progress_course_idx\` ON \`eg_lesson_progress\` (\`course_id\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lesson_progress_completed_idx\` ON \`eg_lesson_progress\` (\`completed\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lesson_progress_updated_at_idx\` ON \`eg_lesson_progress\` (\`updated_at\`)`,
  `CREATE INDEX IF NOT EXISTS \`eg_lesson_progress_created_at_idx\` ON \`eg_lesson_progress\` (\`created_at\`)`,
]

/**
 * The admin area's record of who has a document open. It gains one column per
 * collection, which is why it is altered rather than created here - it belongs
 * to the engine, not to this feature.
 */
const LOCKED_DOCUMENT_COLUMNS: { column: string; definition: string }[] = [
  { column: 'eg_courses_id', definition: '`eg_courses_id` integer REFERENCES "eg_courses"(id)' },
  { column: 'eg_lessons_id', definition: '`eg_lessons_id` integer REFERENCES "eg_lessons"(id)' },
  { column: 'eg_enrolments_id', definition: '`eg_enrolments_id` integer REFERENCES "eg_enrolments"(id)' },
  {
    column: 'eg_lesson_progress_id',
    definition: '`eg_lesson_progress_id` integer REFERENCES "eg_lesson_progress"(id)',
  },
]

const LOCKED_DOCUMENT_INDEXES = [
  'CREATE INDEX IF NOT EXISTS `eg_locked_documents_rels_eg_courses_id_idx` ON `eg_locked_documents_rels` (`eg_courses_id`)',
  'CREATE INDEX IF NOT EXISTS `eg_locked_documents_rels_eg_lessons_id_idx` ON `eg_locked_documents_rels` (`eg_lessons_id`)',
  'CREATE INDEX IF NOT EXISTS `eg_locked_documents_rels_eg_enrolments_id_idx` ON `eg_locked_documents_rels` (`eg_enrolments_id`)',
  'CREATE INDEX IF NOT EXISTS `eg_locked_documents_rels_eg_lesson_progress_id_idx` ON `eg_locked_documents_rels` (`eg_lesson_progress_id`)',
]

export async function up({ db, payload: engine }: MigrateUpArgs): Promise<void> {
  for (const statement of TABLES) {
    await db.run(sql.raw(statement))
  }
  for (const statement of INDEXES) {
    await db.run(sql.raw(statement))
  }
  engine.logger.info('[migrate] Course tables are present.')

  const columnsOf = async (table: string): Promise<Set<string>> => {
    const rows = (await db.all(
      sql`SELECT name FROM sqlite_master WHERE type='table' AND name=${table}`,
    )) as { name: string }[]
    if (rows.length === 0) return new Set()
    const info = (await db.all(sql.raw(`PRAGMA table_info(\`${table}\`)`))) as { name: string }[]
    return new Set(info.map((row) => row.name))
  }

  const locked = await columnsOf('eg_locked_documents_rels')
  if (locked.size === 0) {
    // The engine's own table is missing, which means the base migration has not
    // run here. Leave it alone rather than guessing at its shape.
    engine.logger.warn('[migrate] eg_locked_documents_rels is absent - skipping its course columns.')
    return
  }

  const added: string[] = []
  for (const { column, definition } of LOCKED_DOCUMENT_COLUMNS) {
    if (locked.has(column)) continue
    await db.run(sql.raw(`ALTER TABLE \`eg_locked_documents_rels\` ADD ${definition}`))
    added.push(column)
  }
  for (const statement of LOCKED_DOCUMENT_INDEXES) {
    await db.run(sql.raw(statement))
  }

  if (added.length > 0) engine.logger.info(`[migrate] Added to eg_locked_documents_rels: ${added.join(', ')}`)
}

export async function down({ payload: engine }: MigrateDownArgs): Promise<void> {
  // No-op, matching the other migrations here. Dropping these would take every
  // enrolment and every lesson a learner has ticked off with them, and the
  // Courses toggle already hides the whole feature without deleting a row.
  engine.logger.info('[migrate] Down is a no-op - course tables and progress are left in place.')
}
