/**
 * The full DB-side sequence run by `/api/internal-migrate/route.ts`'s POST
 * handler, extracted into a plain function so it can be run in a test
 * against a genuinely empty D1 (`getPlatformProxy({ persist: false })`)
 * without going through Next.js request machinery - no test in this project
 * imports a route file directly (checked: no precedent anywhere under
 * `tests/`), so this had to be a real module either way once the
 * fresh-install acceptance proof needed to exercise the route's actual
 * sequence rather than a hand-copied approximation of it.
 *
 * THE FRESH-INSTALL GAP THIS CLOSES (found 2026-09-17, see
 * payload-removal-plan.md's "Fresh-install / deploy-button acceptance
 * requirement" section for the full writeup): of this app's 18 real
 * migrations (`src/migrations/index.ts`), the route previously only ever ran
 * the LAST 7 (`RUNNABLE_MIGRATIONS`, now `LATE_MIGRATIONS` below) - the
 * hand-written ones proven safe to replay on an already-migrated database.
 * The FIRST 5 create the foundational ~150 tables (users, pages, posts,
 * media, site settings, ecommerce, events, ...) and were excluded because
 * they are NOT safe to replay on an already-migrated database (no `IF NOT
 * EXISTS` guards - they were generated by the CLI in the ordinary,
 * non-idempotent way). That made them the one and only source of those base
 * tables, and a genuinely fresh D1 (a new Cloudflare account clicking the
 * deploy button) had no path to get them at all.
 *
 * Confirmed via a live production D1 console query that all 5 of these
 * migrations ARE already recorded in production's `eg_migrations` bookkeeping
 * table (real historical timestamps, from before this route's
 * `RUNNABLE_MIGRATIONS` allowlist was narrowed down to just the last 7). That
 * is what makes adding them back safe: `runMigrations` (`@/localapi/migrate`)
 * skips any migration whose name is already recorded, checked BEFORE calling
 * its `up()` - so on production and on this dev's own already-migrated local
 * D1, `EARLY_MIGRATIONS` is a pure no-op (all 5 skipped), while on a
 * genuinely empty database it runs them for real.
 *
 * ORDERING - the part that isn't just "add them to the list". These 5
 * migrations create tables under their ORIGINAL, pre-`eg_`-prefix names
 * (`users`, `pages`, `posts`, `media`, `payload_locked_documents_rels`, ...).
 * The `eg_` rename is itself a LATER migration
 * (`20260825_033000_rename_tables_eg_prefix`/`20260826_090000_rename_engine_tables`,
 * both excluded here - see the bottom of this comment) whose idempotent
 * equivalent is this route's own `renameTables`/`bootstrapEngineTables`
 * calls. Three things all have to happen in the right order relative to that
 * rename for a fresh install to end up both correctly SHAPED and correctly
 * NAMED:
 *
 *  - The `page-builder`/`settings` entries of `SCHEMA_SETS` still name the
 *    PRE-rename content tables (`posts`, `pages`, ...) - see
 *    `./schema/freshInstallSchemaSets.ts`'s own doc comment - so they have to
 *    run AFTER `EARLY_MIGRATIONS` creates those tables but BEFORE the content
 *    rename (`renameTables(TABLE_RENAMES)`) below retires those names.
 *  - The `locked-documents-rels` entry of `SCHEMA_SETS`, by contrast, already
 *    names the POST-rename table (`eg_locked_documents_rels` - it is
 *    hand-written, not generated, and was written after the cutover). That
 *    table only exists once the engine-bookkeeping rename
 *    (`payload_locked_documents_rels` -> `eg_locked_documents_rels`, part of
 *    `bootstrapEngineTables`) has run - which is why `bootstrapEngineTables`
 *    runs a SECOND time right after `EARLY_MIGRATIONS`, before `SCHEMA_SETS`,
 *    rather than only at the very top. (Its FK columns reference
 *    `eg_audit_log`/`eg_backups`/etc, which don't exist yet at this point -
 *    confirmed empirically against a real D1 proxy that SQLite/D1 does not
 *    validate a `REFERENCES` target's existence at `ALTER TABLE ADD COLUMN`
 *    time, only the table being altered, so this is not a problem.)
 *  - The content-table rename (`renameTables(TABLE_RENAMES)`) then runs AFTER
 *    `SCHEMA_SETS`, carrying the additive columns/tables it just added over
 *    to the `eg_` names along with everything else.
 *
 * Both `bootstrapEngineTables` and `renameTables` are idempotent by
 * construction (each checks `exists`/`tableExists` before acting - see their
 * own doc comments), so calling `bootstrapEngineTables` twice is a no-op
 * wherever the first pass already did the work (any database that isn't a
 * fresh install) and does the real work exactly once wherever it was still
 * needed.
 *
 * Full sequence, in order:
 *  1. `bootstrapEngineTables` (1st pass) - ensures `eg_migrations` exists
 *     (needed so `runMigrations`' skip-by-name check has something to read)
 *     and fixes any already-partially-renamed engine bookkeeping on a
 *     database that is mid-upgrade rather than fresh. A no-op beyond
 *     creating that one empty table on a genuinely fresh database.
 *  2. `EARLY_MIGRATIONS` - the 5 foundation migrations. No-op wherever
 *     already recorded (production, local dev); creates the base schema
 *     under pre-`eg_`-prefix names on a fresh install.
 *  3. `bootstrapEngineTables` (2nd pass) - renames the engine bookkeeping
 *     tables `EARLY_MIGRATIONS` just created (`payload_migrations` was
 *     already handled in pass 1; `payload_preferences(_rels)`,
 *     `payload_locked_documents(_rels)`, `payload_kv`) onto the `eg_`
 *     prefix, and renames every `_rels` table's relationship columns
 *     (content tables included - column renames don't depend on whether the
 *     referenced table itself has been renamed yet). No-op everywhere else.
 *  4. `SCHEMA_SETS` (page-builder / settings / locked-documents-rels
 *     additions) - see the ordering discussion above for why this sits here.
 *  5. `renameTables(TABLE_RENAMES)` - moves the content tables
 *     `EARLY_MIGRATIONS`/`SCHEMA_SETS` just created/extended onto the `eg_`
 *     prefix. No-op everywhere else (already renamed).
 *  6. `LATE_MIGRATIONS` - the 7 hand-written, already-idempotent,
 *     already-`eg_`-prefixed migrations (unchanged from the previous
 *     `RUNNABLE_MIGRATIONS`).
 *
 * Deliberately still excluded from both migration lists (unchanged from
 * before): the 6 migrations in between (`seed_home_and_templates`,
 * `fix_blocks_rels_tables`, `builder_sections_loops_custom_fields`,
 * `settings_globals_and_features`, `rename_tables_eg_prefix`,
 * `rename_engine_tables`) - each already has its own separate,
 * production-proven idempotent mechanism elsewhere in this pipeline
 * (`/api/internal-seed`, the raw SQL files in `deploy:database`,
 * `SCHEMA_SETS`, and this file's own rename/bootstrap calls, respectively).
 * Running them here too would either throw (non-idempotent SQL) or
 * double-apply.
 */
import { drizzle } from 'drizzle-orm/d1'

import { runMigrations, type Drizzle, type MigrationEntry } from '@/localapi/migrate'
import type { EngineLogger } from '@/localapi/logger'
import { migrations as ALL_MIGRATIONS } from '@/migrations'

import { renameTables } from './schema/applyRenames'
import { applySchemaAdditions } from './schema/applySchema'
import { bootstrapEngineTables, type EngineDb } from './schema/engineBootstrap'
import { ENGINE_TABLE_RENAMES } from './schema/engineTables'
import { SCHEMA_SETS, withoutRenamedTables } from './schema/freshInstallSchemaSets'
import { TABLE_RENAMES } from './schema/tableRenames'

const REAL_MIGRATIONS = ALL_MIGRATIONS as unknown as MigrationEntry[]

// See this file's header comment: the barrel's first 5 entries create the
// foundational, pre-`eg_`-prefix base schema; the last 7 are the
// hand-written, already-idempotent, already-`eg_`-prefixed ones. The 6 in
// between are deliberately excluded - see the header comment for why.
export const EARLY_MIGRATIONS: MigrationEntry[] = REAL_MIGRATIONS.slice(0, 5)
export const LATE_MIGRATIONS: MigrationEntry[] = REAL_MIGRATIONS.slice(11)

export type InternalMigrateResult = {
  results: Record<string, unknown>
  errorCount: number
}

/**
 * Runs the full sequence against a real D1 binding (production, or a test's
 * own `getPlatformProxy({ persist: false })` proxy - anything implementing
 * the standard `D1Database` interface). See this file's header comment for
 * the sequence and why each step is ordered where it is.
 */
export async function runInternalMigrate(rawDb: D1Database, logger: EngineLogger): Promise<InternalMigrateResult> {
  const results: Record<string, unknown> = {}
  let errorCount = 0

  const db = drizzle(rawDb) as unknown as Drizzle

  const tableExists = async (table: string): Promise<boolean> => {
    const result = await rawDb.prepare(`SELECT name FROM sqlite_master WHERE type='table' AND name=?`).bind(table).all()
    return (result.results?.length ?? 0) > 0
  }

  const columnsOf = async (table: string): Promise<string[]> => {
    if (!(await tableExists(table))) return []
    const result = await rawDb.prepare(`PRAGMA table_info(\`${table}\`)`).all()
    return (result.results as { name: string }[]).map((row) => row.name)
  }

  const listTables = async (): Promise<string[]> => {
    const result = await rawDb.prepare(`SELECT name FROM sqlite_master WHERE type='table'`).all()
    return (result.results as { name: string }[]).map((row) => row.name)
  }

  const engineDb: EngineDb = {
    exists: tableExists,
    listTables,
    columnsOf,
    run: (statement) => rawDb.prepare(statement).run(),
    countRows: async (table) => {
      const result = await rawDb.prepare(`SELECT COUNT(*) AS n FROM \`${table}\``).all()
      return (result.results?.[0] as { n: number } | undefined)?.n ?? 0
    },
  }

  // Step 1: engine bookkeeping bootstrap, 1st pass - see header comment.
  const engineReportPassA = await bootstrapEngineTables(engineDb)
  errorCount += engineReportPassA.columns.errors.length + engineReportPassA.tables.errors.length
  results['engine-tables'] = engineReportPassA

  // Step 2: the foundation migrations.
  try {
    const early = await runMigrations({ db, engineDb, logger, migrations: EARLY_MIGRATIONS })
    results['foundation-migrations'] = { applied: early.ran, alreadyApplied: early.skipped.length }
  } catch (err) {
    errorCount += 1
    results['foundation-migrations'] = { error: err instanceof Error ? err.message : String(err) }
  }

  // Step 3: engine bookkeeping bootstrap, 2nd pass - has to happen here, not
  // only at the top, so `eg_locked_documents_rels` (needed by the
  // `locked-documents-rels` schema set next) exists on a fresh install. See
  // header comment.
  const engineReportPassB = await bootstrapEngineTables(engineDb)
  errorCount += engineReportPassB.columns.errors.length + engineReportPassB.tables.errors.length
  results['engine-tables-second-pass'] = engineReportPassB

  // Step 4: additive schema sets, computed against the database as it stands
  // right now (pre-content-rename on a fresh install; already-renamed
  // everywhere else) - see `withoutRenamedTables`'s own doc comment.
  const presentBeforeRename = new Set(await listTables())
  const renamedAwayBeforeRename = new Set(
    [...TABLE_RENAMES, ...ENGINE_TABLE_RENAMES].filter((entry) => presentBeforeRename.has(entry.to)).map((entry) => entry.from),
  )

  for (const rawSet of SCHEMA_SETS) {
    const set = withoutRenamedTables(rawSet, renamedAwayBeforeRename)
    const report = await applySchemaAdditions({
      tables: set.tables,
      columns: set.columns,
      indexes: set.indexes,
      run: (statement) => rawDb.prepare(statement).run(),
      columnsOf,
    })
    errorCount += report.errors.length
    results[rawSet.name] = report
  }

  // Step 5: rename the content tables to the `eg_` prefix - has to run AFTER
  // `SCHEMA_SETS` so it carries those additions over under the new names.
  const renameReport = await renameTables({
    renames: TABLE_RENAMES,
    exists: tableExists,
    rename: (from, to) => rawDb.prepare(`ALTER TABLE \`${from}\` RENAME TO \`${to}\``).run(),
  })
  errorCount += renameReport.errors.length
  results['table-renames'] = renameReport

  // Step 6: the hand-written, already-idempotent, already-`eg_`-prefixed
  // migrations (forms, multilingual, backups, members, courses, A/B testing,
  // security audit log) - unchanged from the previous `RUNNABLE_MIGRATIONS`.
  try {
    const late = await runMigrations({ db, engineDb, logger, migrations: LATE_MIGRATIONS })
    results['feature-migrations'] = { applied: late.ran, alreadyApplied: late.skipped.length }
  } catch (err) {
    errorCount += 1
    results['feature-migrations'] = { error: err instanceof Error ? err.message : String(err) }
  }

  return { results, errorCount }
}
