import { applySpeedHeaders, AUTH_COOKIE } from './headers'
import { openEdgeCache } from './purge'
import { getSpeedSettings } from './settings'
import type { ResolvedSpeed } from './types'

const hasSession = (request: Request): boolean =>
  (request.headers.get('cookie') || '').split(';').some((part) => part.trim().startsWith(`${AUTH_COOKIE}=`))

/**
 * Serves a page from the Worker's edge cache, or builds it and stores it.
 *
 * This exists because setting Cache-Control alone is not enough here. A
 * response *generated by* a Worker is not put into Cloudflare's cache
 * automatically the way an origin response is - the header only reaches the
 * visitor's browser. To get a shared, purgeable copy at the edge, the Worker
 * has to write it there itself, which is what this does.
 *
 * Only GET requests for anonymous visitors are stored, unless "cache logged-in
 * users" is on. Range and conditional requests are passed straight through
 * because a partial response is not a page.
 */
export async function withPageCache(
  request: Request,
  build: () => Promise<Response>,
  settings?: ResolvedSpeed,
): Promise<Response> {
  const speed = settings ?? (await getSpeedSettings())
  const url = new URL(request.url)

  const eligible =
    speed.enabled &&
    speed.caching.pageCache &&
    request.method === 'GET' &&
    !request.headers.has('range') &&
    (!hasSession(request) || speed.caching.cacheLoggedInUsers)

  if (!eligible) {
    return applySpeedHeaders(await build(), speed, { pathname: url.pathname, request })
  }

  const cache = await openEdgeCache()
  const key = `${url.origin}${url.pathname}${url.search}`

  if (cache) {
    try {
      const hit = await cache.match(key)
      if (hit) {
        const headers = new Headers(hit.headers)
        headers.set('x-speed-cache', 'hit')
        return new Response(hit.body, { status: hit.status, statusText: hit.statusText, headers })
      }
    } catch {
      // A cache read failure is never a reason not to serve the page.
    }
  }

  const fresh = applySpeedHeaders(await build(), speed, { pathname: url.pathname, request })

  // Storing an error page would pin the failure in place for a whole TTL.
  if (cache && fresh.status === 200) {
    try {
      const stored = fresh.clone()
      const headers = new Headers(stored.headers)
      headers.set('x-speed-cache', 'stored')
      await cache.put(key, new Response(stored.body, { status: 200, headers }))
    } catch {
      // Body already consumed, or the runtime refused the entry. Serve anyway.
    }
  }

  return fresh
}
