import { getCloudflareContext } from '@opennextjs/cloudflare'
import { NextResponse } from 'next/server'

import type { SchemaColumn, SchemaIndex, SchemaTable } from '@/migrations/schema/builderSchema'

import { renameTables } from '@/migrations/schema/applyRenames'
import { applySchemaAdditions } from '@/migrations/schema/applySchema'
import { bootstrapEngineTables } from '@/migrations/schema/engineBootstrap'
import { ENGINE_TABLE_RENAMES } from '@/migrations/schema/engineTables'
import { NEW_COLUMNS, NEW_INDEXES, NEW_TABLES } from '@/migrations/schema/builderSchema'
import { SETTINGS_COLUMNS, SETTINGS_INDEXES, SETTINGS_TABLES } from '@/migrations/schema/settingsSchema'
import { TABLE_RENAMES } from '@/migrations/schema/tableRenames'
import { hasInternalRouteKey } from '@/utilities/internalRouteGuard'
import { getEngine } from '@/lib/engine'

import * as migration_20260827_100000_security_audit_log from '@/migrations/20260827_100000_security_audit_log'
import * as migration_20260828_110000_forms from '@/migrations/20260828_110000_forms'
import * as migration_20260828_120000_multilingual from '@/migrations/20260828_120000_multilingual'
import * as migration_20260828_130000_backups from '@/migrations/20260828_130000_backups'
import * as migration_20260830_110000_members from '@/migrations/20260830_110000_members'
import * as migration_20260830_120000_courses from '@/migrations/20260830_120000_courses'
import * as migration_20260830_130000_ab_testing from '@/migrations/20260830_130000_ab_testing'

// These are the migrations written after this route's static schema-diff
// mechanism was built. Each one says so in its own header comment, but the
// short version: `payload migrate` can only ever reach a local emulated D1 in
// this project's CI, never the real database (see the note on the D1 binding
// in wrangler.jsonc) - and the CLI's migration *runner*, called
// programmatically, discovers its file list with `fs.readdirSync` against a
// directory that does not exist inside the deployed Worker bundle. So this
// route calls the engine's own `db.migrate()` directly, handing it this exact
// list instead of letting it try to read the filesystem - the one part of the
// runner (transaction handling, recording each name into `eg_migrations`)
// that *does* work identically whether it is invoked from the CLI or from
// here, once the file list itself is supplied.
//
// Deliberately NOT the full history: every migration listed here documents
// itself as hand-written to be safe to replay against a database that may
// already have its tables (`CREATE TABLE IF NOT EXISTS`, columns added
// defensively). The migrations before this one were generated by the CLI in
// the ordinary, non-idempotent way and assume a clean sequential apply; running
// those here on a database that already has their tables would throw on the
// very first one and abort the whole batch. Add new hand-written, idempotent
// migrations to this list as they are created.
const RUNNABLE_MIGRATIONS = [
  {
    up: migration_20260827_100000_security_audit_log.up,
    down: migration_20260827_100000_security_audit_log.down,
    name: '20260827_100000_security_audit_log',
  },
  {
    up: migration_20260828_110000_forms.up,
    down: migration_20260828_110000_forms.down,
    name: '20260828_110000_forms',
  },
  {
    up: migration_20260828_120000_multilingual.up,
    down: migration_20260828_120000_multilingual.down,
    name: '20260828_120000_multilingual',
  },
  {
    up: migration_20260828_130000_backups.up,
    down: migration_20260828_130000_backups.down,
    name: '20260828_130000_backups',
  },
  {
    up: migration_20260830_110000_members.up,
    down: migration_20260830_110000_members.down,
    name: '20260830_110000_members',
  },
  {
    up: migration_20260830_120000_courses.up,
    down: migration_20260830_120000_courses.down,
    name: '20260830_120000_courses',
  },
  {
    up: migration_20260830_130000_ab_testing.up,
    down: migration_20260830_130000_ab_testing.down,
    name: '20260830_130000_ab_testing',
  },
]

// Applies every additive schema change straight against the live D1 binding,
// from inside the deployed Worker.
//
// Why this exists rather than the CLI's `migrate`: in this project's Cloudflare
// Workers Build environment, that command can only ever reach a local
// emulated D1, never the real database (see the note on the D1 binding in
// wrangler.jsonc). Running the DDL through the Worker's own binding is the one
// path guaranteed to hit production.
//
// Every statement is idempotent (see applySchemaAdditions), so re-running this
// on an already-migrated database is a no-op - which is what makes it safe to
// call on every deploy.
//
// Guarded by INTERNAL_ROUTE_KEY (see utilities/internalRouteGuard). It only
// ever adds tables, columns and indexes and can never drop or modify existing
// data - but each call runs unbounded D1 work, so it is not something to leave
// open to the internet.

/** Schema sets are applied in order; later sets may depend on earlier ones. */
const SCHEMA_SETS = [
  { name: 'page-builder', tables: NEW_TABLES, columns: NEW_COLUMNS, indexes: NEW_INDEXES },
  { name: 'settings', tables: SETTINGS_TABLES, columns: SETTINGS_COLUMNS, indexes: SETTINGS_INDEXES },
]

/**
 * Pulls the table an index is created on out of its `CREATE INDEX ... ON
 * \`table\` (...)` statement, so index entries can be filtered by table like
 * the table and column entries already are.
 */
const indexTarget = (statement: string): string =>
  statement.match(/\sON\s+`([^`]+)`/)?.[1] ?? ''

/**
 * The schema sets above were generated before the rename and still name the
 * pre-`eg_` tables. Once a table has been renamed, its old name must not be
 * touched again: `CREATE TABLE IF NOT EXISTS \`pages_blocks_hero\`` would
 * happily create a second, empty table under the retired name.
 *
 * So every entry whose table has already moved is dropped. That is not a loss -
 * the rename carried those tables, columns and indexes over intact, so the
 * additions are already present under the new name. Entries for tables that
 * have NOT been renamed yet (a database still mid-upgrade) are left in, and the
 * next deploy renames them.
 */
function withoutRenamedTables<T extends { tables: SchemaTable[]; columns: SchemaColumn[]; indexes: SchemaIndex[] }>(
  set: T,
  renamedAway: Set<string>,
): Pick<T, 'tables' | 'columns' | 'indexes'> {
  return {
    tables: set.tables.filter((entry) => !renamedAway.has(entry.table)),
    columns: set.columns.filter((entry) => !renamedAway.has(entry.table)),
    indexes: set.indexes.filter((entry) => !renamedAway.has(indexTarget(entry.sql))),
  }
}

export async function POST(request: Request): Promise<Response> {
  if (!hasInternalRouteKey(request)) {
    return NextResponse.json({ error: 'Not found' }, { status: 404 })
  }

  const { env } = await getCloudflareContext({ async: true })
  const db = env.D1

  if (!db) {
    return NextResponse.json({ error: 'No D1 binding available.' }, { status: 500 })
  }

  const results: Record<string, unknown> = {}
  let errorCount = 0

  const tableExists = async (table: string): Promise<boolean> => {
    const result = await db
      .prepare(`SELECT name FROM sqlite_master WHERE type='table' AND name=?`)
      .bind(table)
      .all()
    return (result.results?.length ?? 0) > 0
  }

  // Renames run FIRST: every additive step below has to see the final table
  // names. Idempotent - a pair is only moved when the old table is still there
  // and the new one is not (see applyRenames), so this is a no-op on an
  // already-renamed database. SQLite carries each table's indexes across the
  // rename; their names keep the old text, which is cosmetic and left alone.
  const columnsOf = async (table: string): Promise<string[]> => {
    if (!(await tableExists(table))) return []
    const result = await db.prepare(`PRAGMA table_info(\`${table}\`)`).all()
    return (result.results as { name: string }[]).map((row) => row.name)
  }

  // The engine's own bookkeeping goes first, and with it the relationship
  // columns inside the locking and preferences `_rels` tables. Those columns
  // are named after the TABLE of the collection they point at, so they had to
  // move when the collections did - leaving them behind is what took the
  // portal down. See migrations/schema/engineBootstrap.ts.
  const engineReport = await bootstrapEngineTables({
    exists: tableExists,
    listTables: async () => {
      const result = await db.prepare(`SELECT name FROM sqlite_master WHERE type='table'`).all()
      return (result.results as { name: string }[]).map((row) => row.name)
    },
    columnsOf,
    run: (statement) => db.prepare(statement).run(),
    countRows: async (table) => {
      const result = await db.prepare(`SELECT COUNT(*) AS n FROM \`${table}\``).all()
      return ((result.results?.[0] as { n: number } | undefined)?.n ?? 0)
    },
  })

  errorCount += engineReport.columns.errors.length + engineReport.tables.errors.length
  results['engine-tables'] = engineReport

  const renameReport = await renameTables({
    renames: TABLE_RENAMES,
    exists: tableExists,
    rename: (from, to) => db.prepare(`ALTER TABLE \`${from}\` RENAME TO \`${to}\``).run(),
  })

  errorCount += renameReport.errors.length
  results['table-renames'] = renameReport

  // Which old names are now gone for good, so the pre-rename schema sets below
  // can skip them instead of recreating them empty.
  const present = new Set(
    (
      (
        await db.prepare(`SELECT name FROM sqlite_master WHERE type='table'`).all()
      )
        .results as { name: string }[]
    ).map((row) => row.name),
  )
  // Engine renames count here too: the schema sets were generated when the
  // locking table was still `payload_locked_documents_rels`, and any entry
  // naming it now targets a table that no longer exists.
  const renamedAway = new Set(
    [...TABLE_RENAMES, ...ENGINE_TABLE_RENAMES]
      .filter((entry) => present.has(entry.to))
      .map((entry) => entry.from),
  )

  for (const rawSet of SCHEMA_SETS) {
    const set = withoutRenamedTables(rawSet, renamedAway)
    const report = await applySchemaAdditions({
      tables: set.tables,
      columns: set.columns,
      indexes: set.indexes,
      run: (statement) => db.prepare(statement).run(),
      columnsOf,
    })

    errorCount += report.errors.length
    results[rawSet.name] = report
  }

  // The hand-written, idempotent migrations (forms, multilingual, backups,
  // members, courses, A/B testing, security audit log) - see the comment on
  // RUNNABLE_MIGRATIONS above for why these run through the engine's own
  // migration runner instead of the ad-hoc schema diff above them.
  try {
    const engine = await getEngine()
    const before = new Set(
      ((await engine.find({ collection: 'payload-migrations', limit: 0, pagination: false })) as {
        docs: { name: string }[]
      }).docs.map((doc) => doc.name),
    )
    await engine.db.migrate({ migrations: RUNNABLE_MIGRATIONS as Parameters<typeof engine.db.migrate>[0]['migrations'] })
    const after = (await engine.find({
      collection: 'payload-migrations',
      limit: 0,
      pagination: false,
    })) as { docs: { name: string }[] }
    const applied = after.docs.map((doc) => doc.name).filter((name) => !before.has(name))
    results['feature-migrations'] = { applied, alreadyApplied: RUNNABLE_MIGRATIONS.length - applied.length }
  } catch (err) {
    errorCount += 1
    results['feature-migrations'] = { error: err instanceof Error ? err.message : String(err) }
  }

  return NextResponse.json({ ok: errorCount === 0, ...results }, { status: errorCount === 0 ? 200 : 500 })
}
